//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Variant:

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
    func.func private @memset(!llvm.ptr, i32, i64) -> !llvm.ptr
    func.func private @memcpy(!llvm.ptr, !llvm.ptr, i64) -> !llvm.ptr
  memref.global @target_address : memref<1xi64> = uninitialized
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
  %c0xFF_i32 = arith.constant 255 : i32
  %c8_i64 = arith.constant 8 : i64
    %c0_i32 = arith.constant 0 : i32
    // locals


    %target = memref.alloc() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %target[%i] : memref<8xi8>
    }
  %target_ptr_idx = memref.extract_aligned_pointer_as_index %target : memref<8xi8> -> index
  %target_ptr_i64 = arith.index_cast %target_ptr_idx : index to i64
  %global_addr = memref.get_global @target_address : memref<1xi64>
  memref.store %target_ptr_i64, %global_addr[%c0] : memref<1xi64>

    memref.dealloc %target : memref<8xi8>
    %reallocated_out = memref.alloc() : memref<8xi8>

  %global_addr_access = memref.get_global @target_address : memref<1xi64>
  %stored_ptr_i64 = memref.load %global_addr_access[%c0] : memref<1xi64>
  %stored_ptr = llvm.inttoptr %stored_ptr_i64 : i64 to !llvm.ptr
  func.call @memset(%stored_ptr, %c0xFF_i32, %c8_i64) : (!llvm.ptr, i32, i64) -> !llvm.ptr
  func.call @exit(%test_success) : (i32) -> ()
    memref.dealloc %reallocated_out : memref<8xi8>
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
