/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: global
 * Target: global
 * Bug type: inter-object, linear OOBA, overflow
 * Access type: direct, read
 * Variant:
 *  - target declared after origin
 *  - distance is checked as is
 *  - target reached by using a auxiliary pointer
 *  - target accessed by using constants
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals
char origin[8] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};
char target[8] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};
__attribute__((section(".data.index"))) volatile char tmp;
__attribute__((section(".data.index"))) volatile char * aux_ptr;
__attribute__((section(".data.index"))) volatile ssize_t reach_index = 0;
int f()
{
  // locals
  _use(target);
  _use(origin);
  if ( !((ssize_t)(GET_ADDR_BITS(target) - GET_ADDR_BITS(origin)) >= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  aux_ptr = &origin[0];
  while( GET_ADDR_BITS(aux_ptr) != GET_ADDR_BITS(target) )
  {
    tmp = *aux_ptr;
    ++aux_ptr;
    _use(&tmp);
  }
  volatile char read_value[8];
  volatile size_t i;
  for (i = 0; i < 8; i++)
  {
    read_value[i] = aux_ptr[i];
  }
  _use(read_value);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
