/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: heap
 * Target: heap
 * Bug type: non-object, type confusion OOBA, overflow
 * Access type: direct, write
 * Variant:
 *  - using load widening
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif
volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";
// types
// globals
int f()
{
  // locals
  char *origin = (char *)malloc( 8 );
  origin[0] = 0xAA;
  origin[1] = 0xAA;
  origin[2] = 0xAA;
  origin[3] = 0xAA;
  origin[4] = 0xAA;
  origin[5] = 0xAA;
  origin[6] = 0xAA;
  origin[7] = 0xAA;
  if ( !(8 >= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  if ( !(8 < (8 + 3) ) ) _exit(PRECONDITIONS_FAILED_VALUE);
  *((volatile uint32_t *)(origin + (8 - 1))) = 0xFFFFFFFF;
  _use(origin);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  free(origin);
  return 0;
}

int main()
{
  f();

  return 0;
}
