//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Memory region: heap
// Bug type: double-free, used-memory
// Access type: stdlib, read
// Variant:
//  - with use-after-free

module {
  // globals

  func.func private @exit(%arg0: i32)  -> ()
  func.func @use(%arg0: memref<8xi8>) -> memref<8xi8> { return %arg0 : memref<8xi8> }

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c8_df = arith.constant 8 : index
    %c0_i8_df = arith.constant 0 : i8
    %c0_i32 = arith.constant 0 : i32
    // locals


    %pointer_to_double_free = memref.alloc() : memref<10xi8> // pointer to be double-freed
    memref.dealloc %pointer_to_double_free : memref<10xi8>
    memref.store %c0_i8_df, %pointer_to_double_free[%c8_df] : memref<10xi8> // use-after-free for heap metadata corruption
    memref.dealloc %pointer_to_double_free : memref<10xi8> // double free
    %pointer_to_use = memref.alloc() : memref<8xi8> // allocate a new object
    %target = memref.alloc() : memref<8xi8>
    
  %read_value_0 = memref.alloca() : memref<8xi8>
  memref.copy %pointer_to_use, %read_value_0 : memref<8xi8> to memref<8xi8>
  func.call @exit(%test_success) : (i32) -> ()

    memref.dealloc %target : memref<8xi8>
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
