//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Memory region: heap
// Bug type: double-free, used-memory
// Access type: direct, read
// Variant:
//  - without use-after-free

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> memref<8xi8> {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c8 = arith.constant 8 : index
    // locals

    %target = memref.alloc() : memref<8xi8>

    %tmp = memref.alloc() : memref<8xi8>
    %tmp2 = memref.alloc() : memref<8xi8>
    %pointer_to_double_free = memref.alloc() : memref<8xi8> // pointer to be double-freed
    memref.dealloc %pointer_to_double_free : memref<8xi8>
    memref.dealloc %tmp : memref<8xi8> // no use after free required
    memref.dealloc %pointer_to_double_free : memref<8xi8> // double free
    %value = memref.load %pointer_to_double_free[%c0] : memref<8xi8> // use-after-free for heap metadata corruption
    func.call @use(%value) : (i8) -> ()
    %pointer_to_use = memref.alloc() : memref<8xi8> // allocate a new object
    %tmp3 = memref.alloc() : memref<8xi8>
    %use_val_tmp2 = memref.load %tmp2[%c0] : memref<8xi8>
    func.call @use(%use_val_tmp2) : (i8) -> ()
    %use_val_tmp3 = memref.load %tmp3[%c0] : memref<8xi8>
    func.call @use(%use_val_tmp3) : (i8) -> ()
    
  scf.for %i = %c0 to %c8 step %c1 {
    %val = memref.load %pointer_to_use[%i] : memref<8xi8>
    func.call @use(%val) : (i8) -> ()
  }
  func.call @exit(%test_success) : (i32) -> ()

    memref.dealloc %target : memref<8xi8>
    %c0_memref = memref.alloca() : memref<8xi8>
    return %c0_memref : memref<8xi8>
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> memref<8xi8>

    return %c0_i32 : i32
  }
}
