//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: heap
// Bug type: inter-object, linear OOBA, underflow
// Access type: direct, write
// Variant:
//  - target declared before origin
//  - target reached using a index

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
    func.func private @memset(!llvm.ptr, i32, i64) -> !llvm.ptr
    func.func private @memcpy(!llvm.ptr, !llvm.ptr, i64) -> !llvm.ptr
  func.func private @exit(%arg0: i32) -> ()
  memref.global @parent : memref<508xi8> = dense<170>

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %distance = arith.constant 500 : index
    %c1 = arith.constant 1 : index
    %c0xFF = arith.constant 255 : i8
    %c8 = arith.constant 8 : index
    %c0_i32 = arith.constant 0 : i32
    // locals


    %parent = memref.get_global @parent : memref<508xi8>
    %parent_target = memref.subview %parent[0][8][1] : memref<508xi8> to memref<8xi8, strided<[1], offset: 0>>
    %parent_origin = memref.subview %parent[500][8][1] : memref<508xi8> to memref<8xi8, strided<[1], offset: 500>>
    %distance_negated = arith.subi %c0, %distance : index
    %use_val_parent_target = memref.load %parent_target[%c0] : memref<8xi8, strided<[1], offset: 0>>
    func.call @use(%use_val_parent_target) : (i8) -> ()
    %use_val_parent_origin = memref.load %parent_origin[%c0] : memref<8xi8, strided<[1], offset: 500>>
    func.call @use(%use_val_parent_origin) : (i8) -> ()
    scf.for %reach_index = %c0 to %c0 step %c1 {
      %index = arith.subi %c0, %reach_index : index
      memref.store %c0xFF, %parent_target[%index] : memref<8xi8, strided<[1], offset: 0>>
    }
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xFF, %parent_target[%i] : memref<8xi8, strided<[1], offset: 0>>
    }
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
