//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: global
// Bug type: non-object, linear OOBA, overflow
// Access type: direct, read
// Variant:
//  - target after origin (overflow)
//  - target reached using a index

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()
  memref.global @origin : memref<8xi8> = dense<170>

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %distance = arith.constant 9 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0_i32 = arith.constant 0 : i32
    // locals


    %origin = memref.get_global @origin : memref<8xi8>
    %distance_negated = arith.subi %c0, %distance : index
    
    %final_reach_index = scf.while (%reach_index = %c0) : (index) -> index {
      %cond = arith.cmpi slt, %reach_index, %c0 : index
      scf.condition(%cond) %reach_index : index
    } do {
    ^bb0(%reach_index: index):
      %val = memref.load %origin[%reach_index] : memref<8xi8>
      func.call @use(%val) : (i8) -> ()
      %next_reach_index = arith.addi %reach_index, %c1 : index
      scf.yield %next_reach_index : index
    }
    scf.for %i = %c0 to %c8 step %c1 {
      %val = memref.load %origin[%i] : memref<8xi8>
      func.call @use(%val) : (i8) -> ()
    }
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
