//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: global
// Bug type: non-object, linear OOBA, underflow
// Access type: direct, read
// Variant:
//  - target before origin (underflow)
//  - distance is checked as is
//  - target reached by using a index
//  - target accessed by using constants

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()
  func.func @use(%arg0: memref<8xi8>) -> memref<8xi8> { return %arg0 : memref<8xi8> }
  memref.global @origin : memref<8xi8> = dense<170>

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %distance = arith.constant 8 : index
    %underflow_dist = arith.constant 8 : index
    %c1 = arith.constant 1 : index
      %__base = arith.constant -8 : index
    %c8 = arith.constant 8 : index
    %c0_i32 = arith.constant 0 : i32
    // locals


    %origin = memref.get_global @origin : memref<8xi8>
    %distance_negated = arith.subi %c0, %distance : index
    scf.for %reach_index = %c0 to %underflow_dist step %c1 {
      %index = arith.subi %c0, %reach_index : index
      %__idx = arith.addi %index, %__base : index
      %val = memref.load %origin[%__idx] : memref<8xi8>
    }
    scf.for %i = %c0 to %c8 step %c1 {
      %__idx = arith.addi %i, %__base : index
      %val = memref.load %origin[%__idx] : memref<8xi8>
    }
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
