//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: heap
// Target: global
// Bug type: inter-object, linear OOBA, underflow
// Access type: direct, write
// Variant:
//  - target declared after origin
//  - distance is negated before checking
//  - target reached by using a index
//  - target accessed by using auxiliary variables

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %c0xBB = arith.constant 187 : i8
    %distance = arith.constant 8 : index
    %c0xFF = arith.constant 255 : i8
    %c0_i32 = arith.constant 0 : i32
    // locals


    %parent = memref.alloc() : memref<16xi8>
    %parent_origin = memref.subview %parent[0][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 0>>
    %parent_target = memref.subview %parent[8][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 8>>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %parent_origin[%i] : memref<8xi8, strided<[1], offset: 0>>
    }
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xBB, %parent_target[%i] : memref<8xi8, strided<[1], offset: 8>>
    }
    %distance_negated = arith.subi %c0, %distance : index
    %use_val_parent_target = memref.load %parent_target[%c0] : memref<8xi8, strided<[1], offset: 8>>
    func.call @use(%use_val_parent_target) : (i8) -> ()
    %use_val_parent_origin = memref.load %parent_origin[%c0] : memref<8xi8, strided<[1], offset: 0>>
    func.call @use(%use_val_parent_origin) : (i8) -> ()
    %negadist_variant = arith.subi %c0, %distance_negated : index
    %final_reach_index = scf.while (%reach_index = %c0) : (index) -> index {
      %cond = arith.cmpi slt, %reach_index, %negadist_variant : index
      scf.condition(%cond) %reach_index : index
    } do {
    ^bb0(%reach_index: index):
      memref.store %c0xFF, %parent_origin[%reach_index] : memref<8xi8, strided<[1], offset: 0>>
      %next_reach_index = arith.subi %reach_index, %c1 : index
      scf.yield %next_reach_index : index
    }
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xFF, %parent_origin[%i] : memref<8xi8, strided<[1], offset: 0>>
    }
    func.call @exit(%test_success) : (i32) -> ()

    memref.dealloc %parent : memref<16xi8>
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
