//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: stack
// Bug type: inter-object, linear OOBA, overflow
// Access type: direct, write
// Variant:
//  - target declared after origin
//  - distance is checked as is
//  - target reached by using a index
//  - target accessed by using auxiliary variables

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()
  func.func @use(%arg0: memref<8xi8>) -> memref<8xi8> { return %arg0 : memref<8xi8> }
  memref.global @parent : memref<48xi8> = dense<170>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c0xFF = arith.constant 255 : i8

  func.func @f() -> i32 {
    // locals


    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %parent = memref.get_global @parent : memref<48xi8>
    %parent_origin = memref.subview %parent[0][8][1] : memref<48xi8> to memref<8xi8>
    %parent_target = memref.subview %parent[40][8][1] : memref<48xi8> to memref<8xi8>
    %distance = arith.constant 40 : index
    %distance_negated = arith.subi %c0, %distance : index
    func.call @use(%parent_target) : (memref<8xi8>) -> ()
    func.call @use(%parent_origin) : (memref<8xi8>) -> ()
    scf.for %reach_index = %c0 to %distance step %c1 {
      memref.store %c0xFF, %parent_origin[%reach_index] : memref<8xi8>
    }
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xFF = arith.constant 255 : i8
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xFF, %parent_origin[%i] : memref<8xi8>
    }
    func.call @exit(%test_success) : (i32) -> ()

    %c0_i32 = arith.constant 0 : i32
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
