//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: heap
// Bug type: inter-object, linear OOBA, overflow
// Access type: stdlib, read
// Variant:
//  - target declared after origin
//  - target reached using a index

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()
  memref.global @parent : memref<828xi8> = dense<170>

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %distance = arith.constant 820 : index
    %c1 = arith.constant 1 : index
    %c1024 = arith.constant 1024 : index
    %c0_i32 = arith.constant 0 : i32
    // locals


    %parent = memref.get_global @parent : memref<828xi8>
    %parent_origin = memref.subview %parent[0][8][1] : memref<828xi8> to memref<8xi8, strided<[1], offset: 0>>
    %parent_target = memref.subview %parent[820][8][1] : memref<828xi8> to memref<8xi8, strided<[1], offset: 820>>
    %distance_negated = arith.subi %c0, %distance : index
    %use_val_parent_target = memref.load %parent_target[%c0] : memref<8xi8, strided<[1], offset: 820>>
    func.call @use(%use_val_parent_target) : (i8) -> ()
    %use_val_parent_origin = memref.load %parent_origin[%c0] : memref<8xi8, strided<[1], offset: 0>>
    func.call @use(%use_val_parent_origin) : (i8) -> ()
    %read_value_184 = memref.alloca() : memref<1024xi8>
    
    %final_i = scf.while (%i = %c0) : (index) -> index {
      %cond = arith.cmpi slt, %i, %c0 : index
      scf.condition(%cond) %i : index
    } do {
    ^bb0(%i: index):
      %remaining = arith.subi %c0, %i : index
      %is_full = arith.cmpi sgt, %remaining, %c1024 : index
      %step = arith.select %is_full, %c1024, %remaining : index
      %src_slice = memref.subview %parent_target[%i][%step][1] : memref<8xi8, strided<[1], offset: 820>> to memref<?xi8, strided<[1], offset: ?>>
      %dst_slice = memref.subview %read_value_184[%c0][%step][1] : memref<1024xi8> to memref<?xi8, strided<[1], offset: ?>>
      memref.copy %src_slice, %dst_slice : memref<?xi8, strided<[1], offset: ?>> to memref<?xi8, strided<[1], offset: ?>>
      %next_i = arith.addi %i, %c1024 : index
      scf.yield %next_i : index
    }
    %use_val_read_value_184 = memref.load %read_value_184[%c0] : memref<1024xi8>
    func.call @use(%use_val_read_value_184) : (i8) -> ()
    %read_value_185 = memref.alloca() : memref<8xi8>
    memref.copy %parent_target, %read_value_185 : memref<8xi8, strided<[1], offset: 820>> to memref<8xi8>
    %use_val_read_value_185 = memref.load %read_value_185[%c0] : memref<8xi8>
    func.call @use(%use_val_read_value_185) : (i8) -> ()
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
