//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: global
// Bug type: intra-object, linear OOBA, underflow
// Access type: direct, write
// Variant:
//  - target declared before origin
//  - distance is negated before checking
//  - target reached by using a index
//  - target accessed by using auxiliary variables

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()
  memref.global @s : memref<16xi8> = dense<170>

  func.func @f() -> memref<8xi8> {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %distance = arith.constant 9 : index
    %distance_negated = arith.constant 9 : index
    %c1 = arith.constant 1 : index
    %c0xFF = arith.constant 255 : i8
    %c8 = arith.constant 8 : index
    // locals


    %s = memref.get_global @s : memref<16xi8>
    %s_target = memref.subview %s[0][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 0>>
    %s_origin = memref.subview %s[8][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 8>>
    %use_val_s_target = memref.load %s_target[%c0] : memref<8xi8, strided<[1], offset: 0>>
    func.call @use(%use_val_s_target) : (i8) -> ()
    %use_val_s_origin = memref.load %s_origin[%c0] : memref<8xi8, strided<[1], offset: 8>>
    func.call @use(%use_val_s_origin) : (i8) -> ()
    
    %is_valid = arith.cmpi sgt, %distance_negated, %c0 : index
    scf.if %is_valid {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    %negadist_variant = arith.subi %c0, %distance_negated : index
    scf.for %reach_index = %c0 to %negadist_variant step %c1 {
      %index = arith.subi %c0, %reach_index : index
      memref.store %c0xFF, %s_origin[%index] : memref<8xi8, strided<[1], offset: 8>>
    }
    
    scf.for %i = %c0 to %c8 step %c1 {
      %idx = arith.addi %i, %distance_negated : index
      memref.store %c0xFF, %s_origin[%idx] : memref<8xi8, strided<[1], offset: 8>>
    }
    func.call @exit(%test_success) : (i32) -> ()

    %c0_memref = memref.alloca() : memref<8xi8>
    return %c0_memref : memref<8xi8>
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> memref<8xi8>

    return %c0_i32 : i32
  }
}
