//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: stack
// Target: stack
// Bug type: intra-object, linear OOBA, overflow
// Access type: direct, read
// Variant:
//  - target declared before origin
//  - target reached using a index

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> memref<8xi8> {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %c0xBB = arith.constant 187 : i8
    %distance = arith.constant -9 : index
    %distance_negated = arith.constant 9 : index
    // locals

    %s = memref.alloca() : memref<16xi8>

    %s_target = memref.subview %s[0][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 0>>
    %s_origin = memref.subview %s[8][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 8>>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %s_target[%i] : memref<8xi8, strided<[1], offset: 0>>
    }
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xBB, %s_origin[%i] : memref<8xi8, strided<[1], offset: 8>>
    }
    %use_val_s_target = memref.load %s_target[%c0] : memref<8xi8, strided<[1], offset: 0>>
    func.call @use(%use_val_s_target) : (i8) -> ()
    %use_val_s_origin = memref.load %s_origin[%c0] : memref<8xi8, strided<[1], offset: 8>>
    func.call @use(%use_val_s_origin) : (i8) -> ()
    
    scf.for %reach_index = %c0 to %c0 step %c1 {
      %val = memref.load %s_target[%reach_index] : memref<8xi8, strided<[1], offset: 0>>
      func.call @use(%val) : (i8) -> ()
    }
    scf.for %i = %c0 to %c8 step %c1 {
      %val = memref.load %s_target[%i] : memref<8xi8, strided<[1], offset: 0>>
      func.call @use(%val) : (i8) -> ()
    }
    func.call @exit(%test_success) : (i32) -> ()

    %c0_memref = memref.alloca() : memref<8xi8>
    return %c0_memref : memref<8xi8>
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> memref<8xi8>

    return %c0_i32 : i32
  }
}
