//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: global
// Bug type: intra-object, linear OOBA, overflow
// Access type: stdlib, read
// Variant:
//  - target declared after origin
//  - target reached using a index

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()
  func.func @use(%arg0: memref<8xi8>) -> memref<8xi8> { return %arg0 : memref<8xi8> }
  memref.global @s : memref<16xi8> = dense<170>

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %distance = arith.constant 8 : index
    %c1 = arith.constant 1 : index
    %c1024 = arith.constant 1024 : index
    %c0_i32 = arith.constant 0 : i32
    // locals


    %s = memref.get_global @s : memref<16xi8>
    %s_origin = memref.subview %s[0][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 0>>
    %s_target = memref.subview %s[8][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 8>>
    %distance_negated = arith.subi %c0, %distance : index
    %read_value_158 = memref.alloca() : memref<1024xi8>
    scf.for %i = %c0 to %c0 step %c1024 {
      %remaining = arith.subi %c0, %i : index
      %is_full = arith.cmpi sgt, %remaining, %c1024 : index
      %step = arith.select %is_full, %c1024, %remaining : index
      %src_slice = memref.subview %s_target[%i][%step][1] : memref<8xi8, strided<[1], offset: 8>> to memref<?xi8, strided<[1], offset: ?>>
      %dst_slice = memref.subview %read_value_158[%c0][%step][1] : memref<1024xi8> to memref<?xi8, strided<[1], offset: ?>>
      memref.copy %src_slice, %dst_slice : memref<?xi8, strided<[1], offset: ?>> to memref<?xi8, strided<[1], offset: ?>>
    }
    %read_value_159 = memref.alloca() : memref<8xi8>
    memref.copy %s_target, %read_value_159 : memref<8xi8, strided<[1], offset: 8>> to memref<8xi8>
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
