//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: stack
// Target: stack
// Bug type: inter-object, linear OOBA, overflow
// Access type: direct, read
// Variant:
//  - target declared before origin
//  - distance is negated before checking
//  - target reached by using a index
//  - target accessed by using auxiliary variables

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
      %__base = arith.constant 1 : index
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0_i32 = arith.constant 0 : i32
    // locals

    %target = memref.alloca() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %target[%i] : memref<8xi8>
    }
    %origin = memref.alloca() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %origin[%i] : memref<8xi8>
    }
    %ptr_target = memref.extract_aligned_pointer_as_index %target : memref<8xi8> -> index
    %ptr_origin = memref.extract_aligned_pointer_as_index %origin : memref<8xi8> -> index
    %distance = arith.subi %ptr_target, %ptr_origin : index
    %distance_negated = arith.subi %c0, %distance : index
    %use_val_target = memref.load %target[%c0] : memref<8xi8>
    func.call @use(%use_val_target) : (i8) -> ()
    %use_val_origin = memref.load %origin[%c0] : memref<8xi8>
    func.call @use(%use_val_origin) : (i8) -> ()
    
    %is_valid = arith.cmpi sle, %distance_negated, %c0 : index
    scf.if %is_valid {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    
    scf.for %reach_index = %c0 to %distance_negated step %c1 {
      %__idx = arith.addi %reach_index, %__base : index
      %val = memref.load %origin[%__idx] : memref<8xi8>
      func.call @use(%val) : (i8) -> ()
    }
    scf.for %i = %c0 to %c8 step %c1 {
      %__idx = arith.addi %i, %__base : index
      %val = memref.load %origin[%__idx] : memref<8xi8>
      func.call @use(%val) : (i8) -> ()
    }
    func.call @exit(%test_success) : (i32) -> ()


    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
