//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: stack
// Target: stack
// Bug type: inter-object, linear OOBA, overflow
// Access type: stdlib, read
// Variant:
//  - target declared after origin
//  - distance is checked as is
//  - target reached by using a index
//  - target accessed by using auxiliary variables

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %c0xBB = arith.constant 187 : i8
    %distance = arith.constant 300 : index
    %c1024 = arith.constant 1024 : index
    %c0_i32 = arith.constant 0 : i32
    // locals

    %parent = memref.alloca() : memref<308xi8>

    %parent_origin = memref.subview %parent[0][8][1] : memref<308xi8> to memref<8xi8, strided<[1], offset: 0>>
    %parent_target = memref.subview %parent[300][8][1] : memref<308xi8> to memref<8xi8, strided<[1], offset: 300>>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %parent_origin[%i] : memref<8xi8, strided<[1], offset: 0>>
    }
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xBB, %parent_target[%i] : memref<8xi8, strided<[1], offset: 300>>
    }
    %distance_negated = arith.subi %c0, %distance : index
    %use_val_parent_target = memref.load %parent_target[%c0] : memref<8xi8, strided<[1], offset: 300>>
    func.call @use(%use_val_parent_target) : (i8) -> ()
    %use_val_parent_origin = memref.load %parent_origin[%c0] : memref<8xi8, strided<[1], offset: 0>>
    func.call @use(%use_val_parent_origin) : (i8) -> ()
    %read_value_46 = memref.alloca() : memref<1024xi8>
    
    %final_i = scf.while (%i = %c0) : (index) -> index {
      %cond = arith.cmpi slt, %i, %distance : index
      scf.condition(%cond) %i : index
    } do {
    ^bb0(%i: index):
      %remaining = arith.subi %distance, %i : index
      %is_full = arith.cmpi sgt, %remaining, %c1024 : index
      %step = arith.select %is_full, %c1024, %remaining : index
      %src_slice = memref.subview %parent_origin[%i][%step][1] : memref<8xi8, strided<[1], offset: 0>> to memref<?xi8, strided<[1], offset: ?>>
      %dst_slice = memref.subview %read_value_46[%c0][%step][1] : memref<1024xi8> to memref<?xi8, strided<[1], offset: ?>>
      memref.copy %src_slice, %dst_slice : memref<?xi8, strided<[1], offset: ?>> to memref<?xi8, strided<[1], offset: ?>>
      %next_i = arith.addi %i, %c1024 : index
      scf.yield %next_i : index
    }
    %use_val_read_value_46 = memref.load %read_value_46[%c0] : memref<1024xi8>
    func.call @use(%use_val_read_value_46) : (i8) -> ()
    %read_value_48 = memref.alloca() : memref<8xi8>
    memref.copy %parent_origin, %read_value_48 : memref<8xi8, strided<[1], offset: 0>> to memref<8xi8>
    %use_val_read_value_48 = memref.load %read_value_48[%c0] : memref<8xi8>
    func.call @use(%use_val_read_value_48) : (i8) -> ()
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
