//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: heap
// Bug type: inter-object, linear OOBA, overflow
// Access type: stdlib, read
// Variant:
//  - target declared after origin
//  - distance is checked as is
//  - target reached by using a auxiliary pointer
//  - target accessed by using auxiliary variables

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()
  func.func @use(%arg0: memref<8xi8>) -> memref<8xi8> { return %arg0 : memref<8xi8> }
  memref.global @parent : memref<91xi8> = dense<170>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c1024 = arith.constant 1024 : index
  %read_value = memref.alloca() : memref<1024xi8>

  func.func @f() -> i32 {
    // locals


    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %parent = memref.get_global @parent : memref<91xi8>
    %parent_origin = memref.subview %parent[0][8][1] : memref<91xi8> to memref<8xi8>
    %parent_target = memref.subview %parent[83][8][1] : memref<91xi8> to memref<8xi8>
    %distance = arith.constant 83 : index
    %distance_negated = arith.subi %c0, %distance : index
    func.call @use(%parent_target) : (memref<8xi8>) -> ()
    func.call @use(%parent_origin) : (memref<8xi8>) -> ()
    scf.for %i = %c0 to %distance step %c1024 {
      %remaining = arith.subi %distance, %i : index
      %is_full = arith.cmpi sgt, %remaining, %c1024 : index
      %step = arith.select %is_full, %c1024, %remaining : index
      %src_slice = memref.subview %parent_origin[%i][%step][1] : memref<8xi8> to memref<?xi8>
      %dst_slice = memref.subview %read_value[%c0][%step][1] : memref<1024xi8> to memref<?xi8>
      memref.copy %src_slice, %dst_slice : memref<?xi8> to memref<?xi8>
    }
    %read_value = memref.alloca() : memref<8xi8>
    memref.copy %parent_origin, %read_value : memref<8xi8> to memref<8xi8>
    func.call @exit(%test_success) : (i32) -> ()

    %c0_i32 = arith.constant 0 : i32
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
