//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: heap
// Target: global
// Bug type: inter-object, linear OOBA, underflow
// Access type: direct, write
// Variant:
//  - target declared after origin
//  - target reached using a index

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()
  memref.global @target : memref<8xi8> = dense<170>

  func.func @f() -> memref<8xi8> {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0xFF = arith.constant 255 : i8
    // locals

    %origin = memref.alloc() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %origin[%i] : memref<8xi8>
    }
    %target = memref.get_global @target : memref<8xi8>
    %ptr_origin = memref.extract_aligned_pointer_as_index %origin : memref<8xi8> -> index
    %ptr_target = memref.extract_aligned_pointer_as_index %target : memref<8xi8> -> index
    %distance = arith.subi %ptr_target, %ptr_origin : index
    %temp = arith.subi %ptr_origin, %ptr_target : index
    %distance_negated = arith.subi %c0, %temp : index

    %use_val_target = memref.load %target[%c0] : memref<8xi8>
    func.call @use(%use_val_target) : (i8) -> ()
    %use_val_origin = memref.load %origin[%c0] : memref<8xi8>
    func.call @use(%use_val_origin) : (i8) -> ()
    %negadist_variant = arith.subi %c0, %c0 : index
    scf.for %reach_index = %c0 to %negadist_variant step %c1 {
      %index = arith.subi %c0, %reach_index : index
      memref.store %c0xFF, %target[%index] : memref<8xi8>
    }
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xFF, %target[%i] : memref<8xi8>
    }
    func.call @exit(%test_success) : (i32) -> ()

    memref.dealloc %origin : memref<8xi8>
    %c0_memref = memref.alloca() : memref<8xi8>
    return %c0_memref : memref<8xi8>
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> memref<8xi8>

    return %c0_i32 : i32
  }
}
