//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: global
// Bug type: non-object, linear OOBA, overflow
// Access type: direct, write
// Variant:
//  - target after origin (overflow)
//  - distance is negated before checking
//  - target reached by using a index
//  - target accessed by using auxiliary variables

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()
  memref.global @origin : memref<8xi8> = dense<170>

  func.func @f() -> memref<8xi8> {
    %c0 = arith.constant 0 : index
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %distance = arith.constant 9 : index
    %c1 = arith.constant 1 : index
    %c0xFF = arith.constant 255 : i8
      %__base = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    // locals

    %origin = memref.get_global @origin : memref<8xi8>

    %distance_negated = arith.subi %c0, %distance : index
    %use_val_origin = memref.load %origin[%c0] : memref<8xi8>
    func.call @use(%use_val_origin) : (i8) -> ()
    
    %is_valid = arith.cmpi sle, %distance_negated, %c0 : index
    scf.if %is_valid {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    
    scf.for %reach_index = %c0 to %distance_negated step %c1 {
      %__idx = arith.addi %reach_index, %__base : index
      memref.store %c0xFF, %origin[%__idx] : memref<8xi8>
    }
    scf.for %i = %c0 to %c8 step %c1 {
      %__idx = arith.addi %i, %__base : index
      memref.store %c0xFF, %origin[%__idx] : memref<8xi8>
    }
    func.call @exit(%test_success) : (i32) -> ()

    %c0_memref = memref.alloca() : memref<8xi8>
    return %c0_memref : memref<8xi8>
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> memref<8xi8>

    return %c0_i32 : i32
  }
}
