//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Memory region: stack
// Bug type: misuse-of-free, used-memory
// Access type: stdlib, read
// Variant:
//  - magic value 0x20

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
  %c8_mof = arith.constant 8 : index
  %c104_mof = arith.constant 104 : index
  %c_magic = arith.constant 32 : i8
  %c0x40 = arith.constant 64 : i8
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0_i32 = arith.constant 0 : i32
    // locals

    %target = memref.alloca() : memref<160xi8>
  memref.store %c_magic, %target[%c8_mof] : memref<160xi8> // magic value
  memref.store %c0x40, %target[%c104_mof] : memref<160xi8>
  %crafted = memref.subview %target[16][8][1] : memref<160xi8> to memref<8xi8, strided<[1], offset: 16>>
  %_ = memref.alloc() : memref<8xi8>
  memref.dealloc %crafted : memref<8xi8, strided<[1], offset: 16>>
  
  %heap_obj = memref.alloc() : memref<8xi8>
  %read_value_4 = memref.alloca() : memref<8xi8>
  memref.copy %heap_obj, %read_value_4 : memref<8xi8> to memref<8xi8>
  func.call @exit(%test_success) : (i32) -> ()


    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
