//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Memory region: heap
// Bug type: misuse-of-free, freed-memory
// Access type: stdlib, write
// Variant:
//  - magic value 0x20

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    // locals


    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %target = memref.alloc() : memref<160xi8>
    
  %c8_mof = arith.constant 8 : index
  %c104_mof = arith.constant 104 : index
  %c_magic = arith.constant 32 : i8
  %c0x40 = arith.constant 64 : i8
  memref.store %c_magic, %target[%c8_mof] : memref<160xi8> // magic value
  memref.store %c0x40, %target[%c104_mof] : memref<160xi8>
  %crafted = memref.subview %target[16][8][1] : memref<160xi8> to memref<8xi8, strided<[1], offset: 16>>
  %_ = memref.alloc() : memref<8xi8>
  memref.dealloc %crafted : memref<8xi8, strided<[1], offset: 16>>
  
  %heap_obj = memref.alloc() : memref<8xi8>

  %target_addr_cmp = memref.extract_aligned_pointer_as_index %target : memref<160xi8> -> index
  %crafted_addr_cmp = memref.extract_aligned_pointer_as_index %crafted : memref<8xi8, strided<[1], offset: 16>> -> index
  %eq_cmp = arith.cmpi eq, %target_addr_cmp, %crafted_addr_cmp : index
  scf.if %eq_cmp {
    memref.dealloc %target : memref<160xi8>
  }
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c8 = arith.constant 8 : index
  %c0xFF = arith.constant 255 : i8
  scf.for %i = %c0 to %c8 step %c1 {
    memref.store %c0xFF, %heap_obj[%i] : memref<8xi8>
  }
  func.call @exit(%test_success) : (i32) -> ()
    %c0_i32 = arith.constant 0 : i32
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
