//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Memory region: heap
// Bug type: misuse-of-free, freed-memory
// Access type: direct, write
// Variant:
//  - magic value 0x20

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
    func.func private @memset(!llvm.ptr, i32, i64) -> !llvm.ptr
    func.func private @memcpy(!llvm.ptr, !llvm.ptr, i64) -> !llvm.ptr
  func.func private @exit(%arg0: i32) -> ()
  llvm.func @free(!llvm.ptr) -> ()

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
  %c8_mof = arith.constant 8 : index
  %c104_mof = arith.constant 104 : index
  %c_magic = arith.constant 32 : i8
  %c0x40 = arith.constant 64 : i8
  %c16_free = arith.constant 16 : index
  %c16_cmp = arith.constant 16 : index
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c8 = arith.constant 8 : index
  %c0xFF = arith.constant 255 : i8
    %c0_i32 = arith.constant 0 : i32
    // locals


    %target = memref.alloc() : memref<160xi8>
    
  memref.store %c_magic, %target[%c8_mof] : memref<160xi8> // magic value
  memref.store %c0x40, %target[%c104_mof] : memref<160xi8>
  %crafted = memref.subview %target[16][8][1] : memref<160xi8> to memref<8xi8, strided<[1], offset: 16>>
  %_ = memref.alloc() : memref<8xi8>
  %target_ptr_free = memref.extract_aligned_pointer_as_index %target : memref<160xi8> -> index
  %crafted_addr_free = arith.addi %target_ptr_free, %c16_free : index
  %crafted_i64_free = arith.index_cast %crafted_addr_free : index to i64
  %crafted_llvm_free = llvm.inttoptr %crafted_i64_free : i64 to !llvm.ptr
  llvm.call @free(%crafted_llvm_free) : (!llvm.ptr) -> ()
  
  %heap_obj = memref.alloc() : memref<8xi8>

  %target_addr_cmp = memref.extract_aligned_pointer_as_index %target : memref<160xi8> -> index
  %crafted_addr_cmp = arith.addi %target_addr_cmp, %c16_cmp : index
  %eq_cmp = arith.cmpi eq, %target_addr_cmp, %crafted_addr_cmp : index
  scf.if %eq_cmp {
    memref.dealloc %target : memref<160xi8>
  }
  scf.for %i = %c0 to %c8 step %c1 {
    memref.store %c0xFF, %heap_obj[%i] : memref<8xi8>
  }
  func.call @exit(%test_success) : (i32) -> ()
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
