//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Memory region: stack
// Bug type: misuse-of-free, used-memory
// Access type: stdlib, read
// Variant:
//  - magic value 0x60

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
    func.func private @memset(!llvm.ptr, i32, i64) -> !llvm.ptr
    func.func private @memcpy(!llvm.ptr, !llvm.ptr, i64) -> !llvm.ptr
  func.func private @exit(%arg0: i32) -> ()
  llvm.func @free(!llvm.ptr) -> ()

  func.func @f() -> i32 {
  %c8_mof = arith.constant 8 : index
  %c104_mof = arith.constant 104 : index
  %c_magic = arith.constant 96 : i8
  %c0x40 = arith.constant 64 : i8
  %c16_free = arith.constant 16 : index
  %c0 = arith.constant 0 : index
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0_i32 = arith.constant 0 : i32
    // locals

    %target = memref.alloca() : memref<160xi8>
  memref.store %c_magic, %target[%c8_mof] : memref<160xi8> // magic value
  memref.store %c0x40, %target[%c104_mof] : memref<160xi8>
  %crafted = memref.subview %target[16][8][1] : memref<160xi8> to memref<8xi8, strided<[1], offset: 16>>
  %_ = memref.alloc() : memref<8xi8>
  %target_ptr_free = memref.extract_aligned_pointer_as_index %target : memref<160xi8> -> index
  %crafted_addr_free = arith.addi %target_ptr_free, %c16_free : index
  %crafted_i64_free = arith.index_cast %crafted_addr_free : index to i64
  %crafted_llvm_free = llvm.inttoptr %crafted_i64_free : i64 to !llvm.ptr
  llvm.call @free(%crafted_llvm_free) : (!llvm.ptr) -> ()
  
  %heap_obj = memref.alloc() : memref<8xi8>
  %read_value_6 = memref.alloca() : memref<8xi8>
  memref.copy %heap_obj, %read_value_6 : memref<8xi8> to memref<8xi8>
  %use_val_read_value_6 = memref.load %read_value_6[%c0] : memref<8xi8>
  func.call @use(%use_val_read_value_6) : (i8) -> ()
  func.call @exit(%test_success) : (i32) -> ()


    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
