//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: global
// Bug type: inter-object, non-linear OOBA, overflow
// Access type: direct, read
// Variant:
//  - target declared after origin

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()
  memref.global @parent : memref<422xi8> = dense<170>

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %distance = arith.constant 414 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0_i32 = arith.constant 0 : i32
    // locals


    %parent = memref.get_global @parent : memref<422xi8>
    %parent_origin = memref.subview %parent[0][8][1] : memref<422xi8> to memref<8xi8, strided<[1], offset: 0>>
    %parent_target = memref.subview %parent[414][8][1] : memref<422xi8> to memref<8xi8, strided<[1], offset: 414>>
    %distance_negated = arith.subi %c0, %distance : index
    scf.for %j = %c0 to %c8 step %c1 {
      %idx = arith.addi %j, %distance : index
      %val = memref.load %parent_origin[%idx] : memref<8xi8, strided<[1], offset: 0>>
    }
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
