//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: global
// Bug type: inter-object, non-linear OOBA, overflow
// Access type: direct, read
// Variant:
//  - target declared after origin

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()
  memref.global @origin : memref<8xi8> = dense<170>
  memref.global @target : memref<8xi8> = dense<170>

  func.func @f() -> i32 {
    %c0 = arith.constant 0 : index
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0_i32 = arith.constant 0 : i32
    // locals

    %origin = memref.get_global @origin : memref<8xi8>
    %target = memref.get_global @target : memref<8xi8>
    %ptr_first = memref.extract_aligned_pointer_as_index %origin : memref<8xi8> -> index
    %ptr_second = memref.extract_aligned_pointer_as_index %target : memref<8xi8> -> index
    %diff = arith.subi %ptr_second, %ptr_first : index
    %minus_diff = arith.subi %c0, %diff : index
    %is_pos = arith.cmpi sgt, %diff, %c0 : index
    %distance = arith.select %is_pos, %diff, %minus_diff : index
    %distance_negated = arith.subi %c0, %distance : index

    %is_valid = arith.cmpi sge, %distance, %c0 : index
    scf.if %is_valid {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    scf.for %j = %c0 to %c8 step %c1 {
      %idx = arith.addi %j, %distance : index
      %val = memref.load %origin[%idx] : memref<8xi8>
      func.call @use(%val) : (i8) -> ()
    }
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
