//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: heap
// Target: stack
// Bug type: inter-object, non-linear OOBA, overflow
// Access type: stdlib, read
// Variant:
//  - target declared after origin

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %c0xBB = arith.constant 187 : i8
    %distance = arith.constant 150 : index
    %c0_i32 = arith.constant 0 : i32
    // locals


    %parent = memref.alloc() : memref<158xi8>
    %parent_origin = memref.subview %parent[0][8][1] : memref<158xi8> to memref<8xi8, strided<[1], offset: 0>>
    %parent_target = memref.subview %parent[150][8][1] : memref<158xi8> to memref<8xi8, strided<[1], offset: 150>>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %parent_origin[%i] : memref<8xi8, strided<[1], offset: 0>>
    }
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xBB, %parent_target[%i] : memref<8xi8, strided<[1], offset: 150>>
    }
    %distance_negated = arith.subi %c0, %distance : index
    %read_value_236 = memref.alloca() : memref<8xi8>
    %src_slice = memref.subview %parent_origin[%distance][8][1] : memref<8xi8, strided<[1], offset: 0>> to memref<8xi8, strided<[1], offset: ?>>
    memref.copy %src_slice, %read_value_236 : memref<8xi8, strided<[1], offset: ?>> to memref<8xi8>
    %use_val_read_value_236 = memref.load %read_value_236[%c0] : memref<8xi8>
    func.call @use(%use_val_read_value_236) : (i8) -> ()
    func.call @exit(%test_success) : (i32) -> ()

    memref.dealloc %parent : memref<158xi8>
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
