//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: heap
// Target: heap
// Bug type: inter-object, non-linear OOBA, overflow
// Access type: direct, read
// Variant:
//  - target declared before origin

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> memref<8xi8> {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    // locals

    %target = memref.alloc() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %target[%i] : memref<8xi8>
    }
    %origin = memref.alloc() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %origin[%i] : memref<8xi8>
    }
    %ptr_target = memref.extract_aligned_pointer_as_index %target : memref<8xi8> -> index
    %ptr_origin = memref.extract_aligned_pointer_as_index %origin : memref<8xi8> -> index
    %distance = arith.subi %ptr_target, %ptr_origin : index
    %temp = arith.subi %ptr_origin, %ptr_target : index
    %distance_negated = arith.subi %c0, %temp : index
    scf.for %j = %c0 to %c8 step %c1 {
      %idx = arith.addi %j, %c0 : index
      %val = memref.load %target[%idx] : memref<8xi8>
      func.call @use(%val) : (i8) -> ()
    }
    func.call @exit(%test_success) : (i32) -> ()


    memref.dealloc %target : memref<8xi8>
    memref.dealloc %origin : memref<8xi8>
    %c0_memref = memref.alloca() : memref<8xi8>
    return %c0_memref : memref<8xi8>
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> memref<8xi8>

    return %c0_i32 : i32
  }
}
