//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: heap
// Bug type: inter-object, non-linear OOBA, overflow
// Access type: stdlib, read
// Variant:
//  - target declared after origin

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()
  memref.global @parent : memref<946xi8> = dense<170>

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %distance = arith.constant 938 : index
    %c0_i32 = arith.constant 0 : i32
    // locals


    %parent = memref.get_global @parent : memref<946xi8>
    %parent_origin = memref.subview %parent[0][8][1] : memref<946xi8> to memref<8xi8, strided<[1], offset: 0>>
    %parent_target = memref.subview %parent[938][8][1] : memref<946xi8> to memref<8xi8, strided<[1], offset: 938>>
    %distance_negated = arith.subi %c0, %distance : index
    %read_value_248 = memref.alloca() : memref<8xi8>
    %src_slice = memref.subview %parent_origin[%distance][8][1] : memref<8xi8, strided<[1], offset: 0>> to memref<8xi8, strided<[1], offset: ?>>
    memref.copy %src_slice, %read_value_248 : memref<8xi8, strided<[1], offset: ?>> to memref<8xi8>
    %use_val_read_value_248 = memref.load %read_value_248[%c0] : memref<8xi8>
    func.call @use(%use_val_read_value_248) : (i8) -> ()
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
