//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: stack
// Bug type: inter-object, non-linear OOBA, overflow
// Access type: stdlib, read
// Variant:
//  - target declared before origin

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()
  memref.global @origin : memref<8xi8> = dense<170>

  func.func @f() -> memref<8xi8> {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    // locals

    %target = memref.alloca() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %target[%i] : memref<8xi8>
    }
    %origin = memref.get_global @origin : memref<8xi8>
    %ptr_target = memref.extract_aligned_pointer_as_index %target : memref<8xi8> -> index
    %ptr_origin = memref.extract_aligned_pointer_as_index %origin : memref<8xi8> -> index
    %distance = arith.subi %ptr_target, %ptr_origin : index
    %distance_negated = arith.subi %c0, %distance : index

    
    %is_valid = arith.cmpi sle, %distance, %c0 : index
    scf.if %is_valid {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    %read_value_349 = memref.alloca() : memref<8xi8>
    %src_slice = memref.subview %origin[%distance][8][1] : memref<8xi8> to memref<8xi8, strided<[1], offset: ?>>
    memref.copy %src_slice, %read_value_349 : memref<8xi8, strided<[1], offset: ?>> to memref<8xi8>
    %use_val_read_value_349 = memref.load %read_value_349[%c0] : memref<8xi8>
    func.call @use(%use_val_read_value_349) : (i8) -> ()
    func.call @exit(%test_success) : (i32) -> ()

    %c0_memref = memref.alloca() : memref<8xi8>
    return %c0_memref : memref<8xi8>
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> memref<8xi8>

    return %c0_i32 : i32
  }
}
