//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: heap
// Target: heap
// Bug type: intra-object, non-linear OOBA, overflow
// Access type: stdlib, read
// Variant:
//  - target declared before origin

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %c0xBB = arith.constant 187 : i8
    %distance = arith.constant 8 : index
    %c0_i32 = arith.constant 0 : i32
    // locals


    %s = memref.alloc() : memref<16xi8>
    %s_target = memref.subview %s[0][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 0>>
    %s_origin = memref.subview %s[8][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 8>>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %s_target[%i] : memref<8xi8, strided<[1], offset: 0>>
    }
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xBB, %s_origin[%i] : memref<8xi8, strided<[1], offset: 8>>
    }
    %distance_negated = arith.subi %c0, %distance : index
    %read_value_185 = memref.alloca() : memref<8xi8>
    %src_slice = memref.subview %s_target[%c0][8][1] : memref<8xi8, strided<[1], offset: 0>> to memref<8xi8, strided<[1], offset: ?>>
    memref.copy %src_slice, %read_value_185 : memref<8xi8, strided<[1], offset: ?>> to memref<8xi8>
    func.call @exit(%test_success) : (i32) -> ()

    memref.dealloc %s : memref<16xi8>
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
