//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: heap
// Bug type: inter-object, non-linear OOBA, overflow
// Access type: stdlib, read
// Variant:
//  - target declared after origin

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()
  memref.global @parent : memref<149xi8> = dense<170>

  func.func @f() -> i32 {
    // locals


    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %parent = memref.get_global @parent : memref<149xi8>
    %parent_origin = memref.subview %parent[0][8][1] : memref<149xi8> to memref<8xi8>
    %parent_target = memref.subview %parent[141][8][1] : memref<149xi8> to memref<8xi8>
    %distance = arith.constant 141 : index
    %distance_negated = arith.subi %c0, %distance : index
    %read_value = memref.alloca() : memref<8xi8>
    %src_slice = memref.subview %parent_origin[distance][8][1] : memref<8xi8> to memref<8xi8>
    memref.copy %src_slice, %read_value : memref<8xi8> to memref<8xi8>
    func.call @exit(%test_success) : (i32) -> ()

    %c0_i32 = arith.constant 0 : i32
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
