//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: heap
// Target: heap
// Bug type: inter-object, non-linear OOBA, overflow
// Access type: stdlib, write
// Variant:
//  - target declared before origin

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %c0xFF = arith.constant 255 : i8
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0_i32 = arith.constant 0 : i32
    // locals

    %target = memref.alloc() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %target[%i] : memref<8xi8>
    }
    %origin = memref.alloc() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %origin[%i] : memref<8xi8>
    }
    %ptr_first = memref.extract_aligned_pointer_as_index %target : memref<8xi8> -> index
    %ptr_second = memref.extract_aligned_pointer_as_index %origin : memref<8xi8> -> index
    %diff = arith.subi %ptr_second, %ptr_first : index
    %minus_diff = arith.subi %c0, %diff : index
    %is_pos = arith.cmpi sgt, %diff, %c0 : index
    %distance = arith.select %is_pos, %diff, %minus_diff : index
    %distance_negated = arith.subi %c0, %distance : index
    scf.for %j = %c0 to %c8 step %c1 {
      %idx = arith.addi %j, %c0 : index
      memref.store %c0xFF, %target[%idx] : memref<8xi8>
    }
    func.call @exit(%test_success) : (i32) -> ()


    memref.dealloc %target : memref<8xi8>
    memref.dealloc %origin : memref<8xi8>
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
