//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: stack
// Target: stack
// Bug type: non-object, type confusion OOBA, overflow
// Access type: direct, write
// Variant:
//  - target after origin (overflow)
//  - using load widening

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %c2 = arith.constant 2 : index
    %c3 = arith.constant 3 : index
    %c8_i32 = arith.constant 8 : i32
    %c16_i32 = arith.constant 16 : i32
    %c24_i32 = arith.constant 24 : i32
    %c0xFFFFFFFF = arith.constant 4294967295 : i32
    %base = arith.constant 7 : index
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %distance = arith.constant 8 : index
    %c0_i32 = arith.constant 0 : i32
    // locals

    %origin = memref.alloca() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %origin[%i] : memref<8xi8>
    }
    %b0 = arith.trunci %c0xFFFFFFFF : i32 to i8
    %w1_tmp = arith.shrsi %c0xFFFFFFFF, %c8_i32  : i32
    %w2_tmp = arith.shrsi %c0xFFFFFFFF, %c16_i32 : i32
    %w3_tmp = arith.shrsi %c0xFFFFFFFF, %c24_i32 : i32
    %b1 = arith.trunci %w1_tmp : i32 to i8
    %b2 = arith.trunci %w2_tmp : i32 to i8
    %b3 = arith.trunci %w3_tmp : i32 to i8
    memref.store %b0, %origin[%base] : memref<8xi8>
    %idx1 = arith.addi %base, %c1 : index
    memref.store %b1, %origin[%idx1] : memref<8xi8>
    %idx2 = arith.addi %base, %c2 : index
    memref.store %b2, %origin[%idx2] : memref<8xi8>
    %idx3 = arith.addi %base, %c3 : index
    memref.store %b3, %origin[%idx3] : memref<8xi8>
    func.call @exit(%test_success) : (i32) -> ()

    %distance_negated = arith.subi %c0, %distance : index

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
