//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: heap
// Target: heap
// Bug type: inter-object, type confusion OOBA, overflow
// Access type: direct, read
// Variant:
//  - target declared after origin
//  - using load widening

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %c0xBB = arith.constant 187 : i8
    %distance = arith.constant 232 : index
    %c2 = arith.constant 2 : index
    %c3 = arith.constant 3 : index
    %c8_i32 = arith.constant 8 : i32
    %c16_i32 = arith.constant 16 : i32
    %c24_i32 = arith.constant 24 : i32
    %base = arith.constant 5 : index
    %c0_i32 = arith.constant 0 : i32
    // locals


    %parent = memref.alloc() : memref<240xi8>
    %parent_origin = memref.subview %parent[0][8][1] : memref<240xi8> to memref<8xi8, strided<[1], offset: 0>>
    %parent_target = memref.subview %parent[232][8][1] : memref<240xi8> to memref<8xi8, strided<[1], offset: 232>>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %parent_origin[%i] : memref<8xi8, strided<[1], offset: 0>>
    }
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xBB, %parent_target[%i] : memref<8xi8, strided<[1], offset: 232>>
    }
    %distance_negated = arith.subi %c0, %distance : index
    %b0 = memref.load %parent_origin[%base] : memref<8xi8, strided<[1], offset: 0>>
    %idx1 = arith.addi %base, %c1 : index
    %b1 = memref.load %parent_origin[%idx1] : memref<8xi8, strided<[1], offset: 0>>
    %idx2 = arith.addi %base, %c2 : index
    %b2 = memref.load %parent_origin[%idx2] : memref<8xi8, strided<[1], offset: 0>>
    %idx3 = arith.addi %base, %c3 : index
    %b3 = memref.load %parent_origin[%idx3] : memref<8xi8, strided<[1], offset: 0>>
    %b0_i32 = arith.extui %b0 : i8 to i32
    %b1_i32 = arith.extui %b1 : i8 to i32
    %b2_i32 = arith.extui %b2 : i8 to i32
    %b3_i32 = arith.extui %b3 : i8 to i32
    %b1_sh = arith.shli %b1_i32, %c8_i32  : i32
    %b2_sh = arith.shli %b2_i32, %c16_i32 : i32
    %b3_sh = arith.shli %b3_i32, %c24_i32 : i32
    %acc0 = arith.ori %b0_i32, %b1_sh : i32
    %acc1 = arith.ori %b2_sh, %b3_sh : i32
    %val = arith.ori %acc0, %acc1 : i32
    func.call @exit(%test_success) : (i32) -> ()

    memref.dealloc %parent : memref<240xi8>
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
