//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: stack
// Target: stack
// Bug type: intra-object, type confusion OOBA, overflow
// Access type: direct, read
// Variant:
//  - target declared before origin
//  - using memref.view to big type

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> memref<8xi8> {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %c0xBB = arith.constant 187 : i8
    %distance = arith.constant 9 : index
    %distance_negated = arith.constant 9 : index
    %big = arith.constant 536870912 : index
    // locals

    %s = memref.alloca() : memref<16xi8>

    %s_target = memref.subview %s[0][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 0>>
    %s_origin = memref.subview %s[8][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 8>>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %s_target[%i] : memref<8xi8, strided<[1], offset: 0>>
    }
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xBB, %s_origin[%i] : memref<8xi8, strided<[1], offset: 8>>
    }
    
    %is_valid = arith.cmpi slt, %distance, %c0 : index
    scf.if %is_valid {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    %cond11 = arith.cmpi sgt, %distance, %c0 : index
    %cond12 = arith.cmpi sgt, %distance, %big : index
    %minus_big = arith.subi %c0, %big : index
    %cond21 = arith.cmpi slt, %distance, %c0 : index
    %cond22 = arith.cmpi slt, %distance, %minus_big : index
    %cond1 = arith.andi %cond11, %cond12 : i1
    %cond2 = arith.andi %cond21, %cond22 : i1
    %big_not_enough = arith.ori %cond1, %cond2 : i1
    scf.if %big_not_enough {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    %viewed = memref.subview %s_origin[0][%big][1] : memref<8xi8, strided<[1], offset: 8>> to memref<?xi8, strided<[1], offset: 8>>
    scf.for %i = %c0 to %distance step %c1 {
      %val = memref.load %viewed[%i] : memref<?xi8, strided<[1], offset: 8>>
      func.call @use(%val) : (i8) -> ()
    }
    scf.for %j = %c0 to %c8 step %c1 {
      %idx = arith.addi %j, %distance : index
      %val2 = memref.load %viewed[%idx] : memref<?xi8, strided<[1], offset: 8>>
      func.call @use(%val2) : (i8) -> ()
    }
    func.call @exit(%test_success) : (i32) -> ()

    %c0_memref = memref.alloca() : memref<8xi8>
    return %c0_memref : memref<8xi8>
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> memref<8xi8>

    return %c0_i32 : i32
  }
}
