//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: global
// Bug type: intra-object, type confusion OOBA, overflow
// Access type: direct, write
// Variant:
//  - target declared after origin
//  - using load widening

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()
  memref.global @s : memref<16xi8> = dense<170>

  func.func @f() -> i32 {
    // locals


    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %s = memref.get_global @s : memref<16xi8>
    %s_origin = memref.subview %s[0][8][1] : memref<16xi8> to memref<8xi8>
    %s_target = memref.subview %s[8][8][1] : memref<16xi8> to memref<8xi8>
    %distance = arith.constant 8 : index
    %distance_negated = arith.subi %c0, %distance : index
    %c0 = arith.constant 0 : index
    %c0xFFFFFFFF = arith.constant 4294967295 : i32
    %casted = memref.reinterpret_cast %s_origin to offset: [7], sizes: [1], strides: [1] : memref<8xi8> to memref<1xi32>
    memref.store %c0xFFFFFFFF, %casted[%c0] : memref<1xi32>
    func.call @exit(%test_success) : (i32) -> ()

    %c0_i32 = arith.constant 0 : i32
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
