//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: heap
// Target: heap
// Bug type: inter-object, type confusion OOBA, overflow
// Access type: direct, write
// Variant:
//  - target declared after origin
//  - using memref.view to big type

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %c0xBB = arith.constant 187 : i8
    %distance = arith.constant 461 : index
    %c2 = arith.constant 2 : index
    %c4 = arith.constant 4 : index
    %c0xFFFFFFFF = arith.constant 4294967295 : i32
    %c0_i32 = arith.constant 0 : i32
    // locals


    %parent = memref.alloc() : memref<469xi8>
    %parent_origin = memref.subview %parent[0][8][1] : memref<469xi8> to memref<8xi8, strided<[1], offset: 0>>
    %parent_target = memref.subview %parent[461][8][1] : memref<469xi8> to memref<8xi8, strided<[1], offset: 461>>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %parent_origin[%i] : memref<8xi8, strided<[1], offset: 0>>
    }
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xBB, %parent_target[%i] : memref<8xi8, strided<[1], offset: 461>>
    }
    %distance_negated = arith.subi %c0, %distance : index
    %viewed = memref.view %parent_origin[%c0][%c2] : memref<8xi8, strided<[1], offset: 0>> to memref<?xi32>
    %distance_div_4 = arith.divsi %distance, %c4 : index
    scf.for %i = %c0 to %distance_div_4 step %c1 {
      memref.store %c0xFFFFFFFF, %viewed[%i] : memref<?xi32>
    }
    scf.for %j = %c0 to %c2 step %c1 {
      %idx = arith.addi %j, %distance_div_4 : index
      memref.store %c0xFFFFFFFF, %viewed[%idx] : memref<?xi32>
    }
    func.call @exit(%test_success) : (i32) -> ()

    memref.dealloc %parent : memref<469xi8>
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
