//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: heap
// Target: heap
// Bug type: non-object, type confusion OOBA, overflow
// Access type: direct, read
// Variant:
//  - target after origin (overflow)
//  - using memref.view to big type

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %distance = arith.constant 9 : index
    %c2 = arith.constant 2 : index
    %c4 = arith.constant 4 : index
    %c0_i32 = arith.constant 0 : i32
    // locals

    %origin = memref.alloc() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %origin[%i] : memref<8xi8>
    }

    %distance_negated = arith.subi %c0, %distance : index
    %viewed = memref.view %origin[%c0][%c2] : memref<8xi8> to memref<?xi32>
    %distance_div_4 = arith.divsi %distance, %c4 : index
    scf.for %i = %c0 to %distance_div_4 step %c1 {
      %val = memref.load %viewed[%i] : memref<?xi32>
      %val_i8 = arith.trunci %val : i32 to i8
      func.call @use(%val_i8) : (i8) -> ()
    }
    scf.for %j = %c0 to %c2 step %c1 {
      %idx = arith.addi %j, %distance_div_4 : index
      %val2 = memref.load %viewed[%idx] : memref<?xi32>
      %val2_i8 = arith.trunci %val2 : i32 to i8
      func.call @use(%val2_i8) : (i8) -> ()
    }
    func.call @exit(%test_success) : (i32) -> ()

    memref.dealloc %origin : memref<8xi8>
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
