//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: heap
// Bug type: inter-object, type confusion OOBA, overflow
// Access type: direct, write
// Variant:
//  - target declared after origin
//  - using load widening

module {
  // globals

  func.func private @exit(%arg0: i32)
  memref.global @parent : memref<806xi8> = dense<170>

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %distance = arith.constant 798 : index
    %idx = arith.constant 7 : index
    %c0xFF = arith.constant 255 : i8
    %c0_i32 = arith.constant 0 : i32
    // locals


    %parent = memref.get_global @parent : memref<806xi8>
    %parent_origin = memref.subview %parent[0][8][1] : memref<806xi8> to memref<8xi8, strided<[1], offset: 0>>
    %parent_target = memref.subview %parent[798][8][1] : memref<806xi8> to memref<8xi8, strided<[1], offset: 798>>
    %distance_negated = arith.subi %c0, %distance : index
    memref.store %c0xFF, %parent_origin[%idx] : memref<8xi8, strided<[1], offset: 0>>
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
