//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: global
// Bug type: inter-object, type confusion OOBA, overflow
// Access type: direct, write
// Variant:
//  - target declared before origin
//  - using memref.view for load widening

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()
  memref.global @target : memref<8xi8> = dense<170>
  memref.global @origin : memref<8xi8> = dense<170>

  func.func @f() -> memref<8xi8> {
    %c0 = arith.constant 0 : index
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c11 = arith.constant 11 : index
    %c1 = arith.constant 1 : index
    %c2 = arith.constant 2 : index
    %c4 = arith.constant 4 : index
    %c0xFFFFFFFF = arith.constant 4294967295 : i32
    // locals

    %target = memref.get_global @target : memref<8xi8>
    %origin = memref.get_global @origin : memref<8xi8>
    %ptr_target = memref.extract_aligned_pointer_as_index %target : memref<8xi8> -> index
    %ptr_origin = memref.extract_aligned_pointer_as_index %origin : memref<8xi8> -> index
    %distance = arith.subi %ptr_target, %ptr_origin : index
    %distance_negated = arith.subi %c0, %distance : index

    
    %is_valid = arith.cmpi slt, %distance, %c0 : index
    scf.if %is_valid {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    %too_far = arith.cmpi sgt, %distance, %c11 : index
    scf.if %too_far {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    %viewed = memref.view %origin[%c4][] : memref<8xi8> to memref<2xi32>
    memref.store %c0xFFFFFFFF, %viewed[%c1] : memref<2xi32>
    func.call @exit(%test_success) : (i32) -> ()

    %c0_memref = memref.alloca() : memref<8xi8>
    return %c0_memref : memref<8xi8>
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> memref<8xi8>

    return %c0_i32 : i32
  }
}
