//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: global
// Bug type: intra-object, type confusion OOBA, overflow
// Access type: direct, read
// Variant:
//  - target declared before origin
//  - using memref.view for load widening

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()
  memref.global @s : memref<16xi8> = dense<170>

  func.func @f() -> memref<8xi8> {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %distance = arith.constant 9 : index
    %c11 = arith.constant 11 : index
    %c1 = arith.constant 1 : index
    %c2 = arith.constant 2 : index
    %c4 = arith.constant 4 : index
    // locals


    %s = memref.get_global @s : memref<16xi8>
    %s_target = memref.subview %s[0][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 0>>
    %s_origin = memref.subview %s[8][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 8>>
    %distance_negated = arith.subi %c0, %distance : index
    
    %is_valid = arith.cmpi slt, %distance, %c0 : index
    scf.if %is_valid {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    %too_far = arith.cmpi sgt, %distance, %c11 : index
    scf.if %too_far {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    %view_s = memref.view %s[ %c4][] : memref<16xi8> to memref<4xi32>
    %viewed = memref.subview %view_s[2][2][1] : memref<4xi32> to memref<2xi32, strided<[1], offset: 2>>
      %val = memref.load %viewed[%c1] : memref<2xi32, strided<[1], offset: 2>>
      %val_i8 = arith.trunci %val : i32 to i8
      func.call @use(%val_i8) : (i8) -> ()
    func.call @exit(%test_success) : (i32) -> ()

    %c0_memref = memref.alloca() : memref<8xi8>
    return %c0_memref : memref<8xi8>
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> memref<8xi8>

    return %c0_i32 : i32
  }
}
