//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: stack
// Target: heap
// Bug type: inter-object, type confusion OOBA, overflow
// Access type: direct, read
// Variant:
//  - target declared after origin
//  - using reinterpret_cast to large memref

module {
  // globals

  func.func private @exit(%arg0: i32)

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %c0xBB = arith.constant 187 : i8
    %distance = arith.constant 920 : index
    %c0_i32 = arith.constant 0 : i32
    // locals

    %parent = memref.alloca() : memref<928xi8>

    %parent_origin = memref.subview %parent[0][8][1] : memref<928xi8> to memref<8xi8, strided<[1], offset: 0>>
    %parent_target = memref.subview %parent[920][8][1] : memref<928xi8> to memref<8xi8, strided<[1], offset: 920>>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %parent_origin[%i] : memref<8xi8, strided<[1], offset: 0>>
    }
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xBB, %parent_target[%i] : memref<8xi8, strided<[1], offset: 920>>
    }
    %distance_negated = arith.subi %c0, %distance : index
    scf.for %j = %c0 to %c8 step %c1 {
      %idx = arith.addi %j, %c0 : index
      %val = memref.load %parent_target[%idx] : memref<8xi8, strided<[1], offset: 920>>
    }
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
