//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: heap
// Bug type: inter-object, type confusion OOBA, overflow
// Access type: direct, write
// Variant:
//  - target declared after origin
//  - using memref.view for load widening

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()
  memref.global @parent : memref<32xi8> = dense<170>

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %distance = arith.constant 24 : index
    %c1 = arith.constant 1 : index
    %c2 = arith.constant 2 : index
    %c4 = arith.constant 4 : index
    %c0xFFFFFFFF = arith.constant 4294967295 : i32
    %c0_i32 = arith.constant 0 : i32
    // locals


    %parent = memref.get_global @parent : memref<32xi8>
    %parent_origin = memref.subview %parent[0][8][1] : memref<32xi8> to memref<8xi8, strided<[1], offset: 0>>
    %parent_target = memref.subview %parent[24][8][1] : memref<32xi8> to memref<8xi8, strided<[1], offset: 24>>
    %distance_negated = arith.subi %c0, %distance : index
    %viewed = memref.view %parent_origin[%c4][] : memref<8xi8, strided<[1], offset: 0>> to memref<2xi32>
    scf.for %i = %c0 to %c2 step %c1 {
      memref.store %c0xFFFFFFFF, %viewed[%i] : memref<2xi32>
    }
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
