//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: global
// Bug type: intra-object, type confusion OOBA, overflow
// Access type: direct, read
// Variant:
//  - target declared after origin
//  - using load widening

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()
  memref.global @s : memref<16xi8> = dense<170>

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %distance = arith.constant 8 : index
    %c1 = arith.constant 1 : index
    %c2 = arith.constant 2 : index
    %c3 = arith.constant 3 : index
    %c8_i32 = arith.constant 8 : i32
    %c16_i32 = arith.constant 16 : i32
    %c24_i32 = arith.constant 24 : i32
    %base = arith.constant 5 : index
    %c0_i32 = arith.constant 0 : i32
    // locals


    %s = memref.get_global @s : memref<16xi8>
    %s_origin = memref.subview %s[0][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 0>>
    %s_target = memref.subview %s[8][8][1] : memref<16xi8> to memref<8xi8, strided<[1], offset: 8>>
    %distance_negated = arith.subi %c0, %distance : index
    %b0 = memref.load %s_origin[%base] : memref<8xi8, strided<[1], offset: 0>>
    %idx1 = arith.addi %base, %c1 : index
    %b1 = memref.load %s_origin[%idx1] : memref<8xi8, strided<[1], offset: 0>>
    %idx2 = arith.addi %base, %c2 : index
    %b2 = memref.load %s_origin[%idx2] : memref<8xi8, strided<[1], offset: 0>>
    %idx3 = arith.addi %base, %c3 : index
    %b3 = memref.load %s_origin[%idx3] : memref<8xi8, strided<[1], offset: 0>>
    %b0_i32 = arith.extui %b0 : i8 to i32
    %b1_i32 = arith.extui %b1 : i8 to i32
    %b2_i32 = arith.extui %b2 : i8 to i32
    %b3_i32 = arith.extui %b3 : i8 to i32
    %b1_sh = arith.shli %b1_i32, %c8_i32  : i32
    %b2_sh = arith.shli %b2_i32, %c16_i32 : i32
    %b3_sh = arith.shli %b3_i32, %c24_i32 : i32
    %acc0 = arith.ori %b0_i32, %b1_sh : i32
    %acc1 = arith.ori %b2_sh, %b3_sh : i32
    %val = arith.ori %acc0, %acc1 : i32
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
