//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: stack
// Target: stack
// Bug type: non-object, type confusion OOBA, overflow
// Access type: direct, read
// Variant:
//  - target after origin (overflow)
//  - using reinterpret_cast to large memref
//  - using a global index

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    // locals

    %origin = memref.alloca() : memref<8xi8>
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %origin[%i] : memref<8xi8>
    }
    %big_origin = memref.reinterpret_cast %origin to offset: [0], sizes: [1024], strides: [1] : memref<8xi8> to memref<1024xi8>
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    scf.for %i = %c0 to %distance step %c1 {
      %val = memref.load %big_origin[%i] : memref<8xi8>
    }
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c1 = arith.constant 1 : index
    scf.for %j = %c0 to %c1 step %c1 {
      %idx = arith.addi %j, %distance : index
      %val = memref.load %big_origin[%idx] : memref<1xi8>
    }
    func.call @exit(%test_success) : (i32) -> ()

    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %distance = arith.constant 8 : index
    %distance_negated = arith.subi %c0, %distance : index

    %c0_i32 = arith.constant 0 : i32
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
