//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: stack
// Target: stack
// Bug type: inter-object, type confusion OOBA, overflow
// Access type: direct, write
// Variant:
//  - target declared after origin
//  - using load widening

module {
  // globals

  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    // locals

    %parent = memref.alloca() : memref<476xi8>

    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %parent_origin = memref.subview %parent[0][8][1] : memref<476xi8> to memref<8xi8>
    %parent_target = memref.subview %parent[468][8][1] : memref<476xi8> to memref<8xi8>
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %parent_origin[%i] : memref<8xi8>
    }
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xBB = arith.constant 187 : i8
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xBB, %parent_target[%i] : memref<8xi8>
    }
    %distance = arith.constant 468 : index
    %distance_negated = arith.subi %c0, %distance : index
    %c0 = arith.constant 0 : index
    %c0xFFFFFFFF = arith.constant 4294967295 : i32
    %casted = memref.reinterpret_cast %parent_origin to offset: [7], sizes: [1], strides: [1] : memref<8xi8> to memref<1xi32>
    memref.store %c0xFFFFFFFF, %casted[%c0] : memref<1xi32>
    func.call @exit(%test_success) : (i32) -> ()

    %c0_i32 = arith.constant 0 : i32
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
