//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: heap
// Target: heap
// Bug type: inter-object, type confusion OOBA, overflow
// Access type: direct, read
// Variant:
//  - target declared before origin
//  - using memref.view for load widening

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> memref<8xi8> {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %c11 = arith.constant 11 : index
    %c2 = arith.constant 2 : index
    %c4 = arith.constant 4 : index
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    // locals

    %target = memref.alloc() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %target[%i] : memref<8xi8>
    }
    %origin = memref.alloc() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %origin[%i] : memref<8xi8>
    }
    %ptr_target = memref.extract_aligned_pointer_as_index %target : memref<8xi8> -> index
    %ptr_origin = memref.extract_aligned_pointer_as_index %origin : memref<8xi8> -> index
    %distance = arith.subi %ptr_target, %ptr_origin : index
    %distance_negated = arith.subi %c0, %distance : index
    
    %is_valid = arith.cmpi slt, %distance, %c0 : index
    scf.if %is_valid {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    %too_far = arith.cmpi sgt, %distance, %c11 : index
    scf.if %too_far {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    %viewed = memref.view %origin[%c4][] : memref<8xi8> to memref<2xi32>
      %val = memref.load %viewed[%c1] : memref<2xi32>
      %val_i8 = arith.trunci %val : i32 to i8
      func.call @use(%val_i8) : (i8) -> ()
    func.call @exit(%test_success) : (i32) -> ()


    memref.dealloc %target : memref<8xi8>
    memref.dealloc %origin : memref<8xi8>
    %c0_memref = memref.alloca() : memref<8xi8>
    return %c0_memref : memref<8xi8>
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> memref<8xi8>

    return %c0_i32 : i32
  }
}
