//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Origin: global
// Target: global
// Bug type: non-object, type confusion OOBA, overflow
// Access type: direct, read
// Variant:
//  - target after origin (overflow)
//  - using load widening

module {
  // globals

  func.func private @exit(%arg0: i32)
  memref.global @origin : memref<8xi8> = dense<170>

  func.func @f() -> i32 {
    // locals


    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %origin = memref.get_global @origin : memref<8xi8>
    %distance = arith.constant 8 : index
    %distance_negated = arith.subi %c0, %distance : index
    %idx = arith.constant 3 : index
    %val = memref.load %origin[%idx] : memref<4xi8>
    func.call @exit(%test_success) : (i32) -> ()

    %c0_i32 = arith.constant 0 : i32
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
