//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Variant:

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    %c0_v = arith.constant 0 : index
    %c8_v = arith.constant 8 : index
  %ctrue = arith.constant 1 : i1
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c8 = arith.constant 8 : index
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0_i32 = arith.constant 0 : i32
    // locals

    %target = memref.alloc() : memref<8xi8>
    %view_target = memref.view %target[%c0_v][%c8_v] : memref<8xi8> to memref<?xi8>
    %reallocated = memref.alloc() : memref<8xi8>

  %target_ptr = memref.extract_aligned_pointer_as_index %target : memref<8xi8> -> index
  %realloc_ptr = memref.extract_aligned_pointer_as_index %reallocated : memref<8xi8> -> index
  %eq = arith.cmpi eq, %target_ptr, %realloc_ptr : index
  %neq = arith.xori %eq, %ctrue : i1
  scf.if %neq {
    func.call @exit(%precond_fail) : (i32) -> ()
  }
  scf.for %i = %c0 to %c8 step %c1 {
    %val = memref.load %view_target[%i] : memref<?xi8>
    func.call @use(%val) : (i8) -> ()
  }
  func.call @exit(%test_success) : (i32) -> ()

    

    memref.dealloc %target : memref<8xi8>
    memref.dealloc %reallocated : memref<8xi8>
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
