//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Variant:
//  - with repeated attempts

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
  %c0_v = arith.constant 0 : index
  %c8_v = arith.constant 8 : index
  %c0_loop = arith.constant 0 : index
  %c1_loop = arith.constant 1 : index
  %c_max_loop = arith.constant 1000000000 : index
  %ctrue_loop = arith.constant 1 : i1
      %c0 = arith.constant 0 : index
      %c1 = arith.constant 1 : index
      %c8 = arith.constant 8 : index
      %c0xAA = arith.constant 170 : i8
    %c0_i32 = arith.constant 0 : i32
    // locals


    %target = memref.alloc() : memref<8xi8>
    
  %view_target = memref.view %target[%c0_v][%c8_v] : memref<8xi8> to memref<?xi8>

    memref.dealloc %target : memref<8xi8>
    %reallocated = memref.alloc() : memref<8xi8>

  %reallocated_while, %counter_while, %not_matched_while = scf.while (%reallocated_iter = %reallocated, %counter_iter = %c0_loop, %not_matched_iter = %ctrue_loop)
      : (memref<8xi8>, index, i1) -> (memref<8xi8>, index, i1) {
    %continue_while = arith.cmpi slt, %counter_iter, %c_max_loop : index
    %cond_while = arith.andi %continue_while, %not_matched_iter : i1
    scf.condition(%cond_while) %reallocated_iter, %counter_iter, %not_matched_iter : memref<8xi8>, index, i1
  } do {
  ^bb0(%reallocated_loop : memref<8xi8>, %counter_loop : index, %not_matched_loop : i1):
    memref.dealloc %reallocated_loop : memref<8xi8>
      %new_reallocated = memref.alloc() : memref<8xi8>
      scf.for %i = %c0 to %c8 step %c1 {
        memref.store %c0xAA, %new_reallocated[%i] : memref<8xi8>
      }
    %target_ptr_loop = memref.extract_aligned_pointer_as_index %target : memref<8xi8> -> index
    %new_ptr_loop = memref.extract_aligned_pointer_as_index %new_reallocated : memref<8xi8> -> index
    %eq_loop = arith.cmpi eq, %target_ptr_loop, %new_ptr_loop : index
    %not_matched_next = arith.xori %eq_loop, %ctrue_loop : i1
    %next_counter_loop = arith.addi %counter_loop, %c1_loop : index
    scf.yield %new_reallocated, %next_counter_loop, %not_matched_next : memref<8xi8>, index, i1
  }
  scf.if %not_matched_while {
    func.call @exit(%precond_fail) : (i32) -> ()
  }
  %read_value_40 = memref.alloca() : memref<8xi8>
  memref.copy %view_target, %read_value_40 : memref<?xi8> to memref<8xi8>
  %use_val_read_value_40 = memref.load %read_value_40[%c0] : memref<8xi8>
  func.call @use(%use_val_read_value_40) : (i8) -> ()
  func.call @exit(%test_success) : (i32) -> ()
    memref.dealloc %reallocated : memref<8xi8>
    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
