//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Memory region: stack
// Bug type: use-after-*, reused memory
// Access type: direct, read
// Variant:
//  - with repeated attempts

module {
  // globals

  memref.global @target_address : memref<1xindex>
  memref.global @target_ptr : memref<1xmemref<8xi8>>
  func.func private @exit(%arg0: i32) -> ()
  memref.global @last_address : memref<1xindex>

  func.func @f() -> i32 {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0_i32 = arith.constant 0 : i32
    // locals

    %target = memref.alloca() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %target[%i] : memref<8xi8>
    }
    %reallocated = memref.alloca() : memref<8xi8>

    %target_addr = memref.extract_aligned_pointer_as_index %target : memref<8xi8> -> index
    %global_addr = memref.get_global @target_address : memref<1xindex>
    memref.store %target_addr, %global_addr[%c0] : memref<1xindex>
    %global_ptr = memref.get_global @target_ptr : memref<1xmemref<8xi8>>
    memref.store %target, %global_ptr[%c0] : memref<1xmemref<8xi8>>
    %realloc_addr = memref.extract_aligned_pointer_as_index %reallocated : memref<8xi8> -> index
    %global_last = memref.get_global @last_address : memref<1xindex>
    %last_addr = memref.load %global_last[%c0] : memref<1xindex>
    %eq_last = arith.cmpi eq, %last_addr, %realloc_addr : index
    scf.if %eq_last {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    memref.store %realloc_addr, %global_last[%c0] : memref<1xindex>
    %global_ptr_access = memref.get_global @target_ptr : memref<1xmemref<8xi8>>
    %saved_ptr = memref.load %global_ptr_access[%c0] : memref<1xmemref<8xi8>>
    scf.for %i = %c0 to %c8 step %c1 {
      %val = memref.load %saved_ptr[%i] : memref<8xi8>
    }

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %c0_main = arith.constant 0 : index
    %c1_main = arith.constant 1 : index
    %cMAX_main = arith.constant 100 : index
    %test_success = arith.constant 42 : i32
    %results = scf.while (%counter = %c0_main) : (index) -> index {
      %lt = arith.cmpi slt, %counter, %cMAX_main : index
      scf.condition(%lt) %counter : index
    } do {
    ^bb0(%counter_iter : index):
    %ret = func.call @f() : () -> i32
      %next_counter = arith.addi %counter_iter, %c1_main : index
      scf.yield %next_counter : index
    }
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }
}
