//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Memory region: stack
// Bug type: use-after-*, reused memory
// Access type: direct, read
// Variant:
//  - with repeated attempts

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()
  memref.global @target_addr : memref<8xi8> = dense<170>
  memref.global @last_address : memref<index>

  func.func @other_f(%arg0:memref<8xi8>) -> i32 {
  %test_success = arith.constant 42 : i32
  %precond_fail = arith.constant 43 : i32
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c8 = arith.constant 8 : index
    // locals
    %reallocated = memref.alloca() : memref<8xi8>
  %target_ptr = memref.extract_aligned_pointer_as_index %arg0 : memref<8xi8> -> index
  %realloc_ptr = memref.extract_aligned_pointer_as_index %reallocated : memref<8xi8> -> index
  %last_address = memref.get_global @last_address : memref<index>
  %val_1 = memref.load %last_address[] : memref<index>
  %eq= arith.cmpi eq, %realloc_ptr, %val_1 : index
  scf.if %eq {
    func.call @exit(%precond_fail) : (i32) -> ()
  }
  memref.store %realloc_ptr, %last_address[] : memref<index>
  %eq_1 = arith.cmpi eq, %target_ptr, %realloc_ptr : index
  scf.if %eq_1 {
    
    
    scf.for %i = %c0 to %c8 step %c1 {
      %val = memref.load %arg0[%i] : memref<8xi8>
      func.call @use(%val) : (i8) -> ()
    }
    func.call @exit(%test_success) : (i32) -> ()

  }
    func.return %precond_fail : i32
  }
  func.func @f(%arg0: memref<8xi8>) -> memref<8xi8> {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %test_success = arith.constant 42 : i32
  %precond_fail = arith.constant 43 : i32
    // locals

    %target = memref.alloca() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %target[%i] : memref<8xi8>
    }
    %val1 = memref.load %target[%c0] : memref<8xi8>
    func.call @use(%val1) : (i8) -> ()

    return %target : memref<8xi8>
  }


  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
  %precond_fail = arith.constant 43 : i32
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c_max = arith.constant 1000000000 : index
  %ctrue = arith.constant 1 : i1
      %cfalse = arith.constant 0 : i1
      %t = memref.alloca() : memref<8xi8>
    %ret = func.call @f(%t) : (memref<8xi8>) -> memref<8xi8>
  scf.for %counter = %c0 to %c_max step %c1 {
    %_ = func.call @other_f(%ret) : (memref<8xi8>) -> i32

    } 
    func.call @exit(%precond_fail) : (i32) -> ()


    return %c0_i32 : i32
  }
}
