//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Variant:
//  - with repeated attempts

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()
  memref.global @last_address : memref<8xi8> = dense<0>

  func.func @f() -> i32 {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0_v = arith.constant 0 : index
    %c8_v = arith.constant 8 : index
    %c0_i32 = arith.constant 0 : i32
    // locals

    %target = memref.alloca() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %target[%i] : memref<8xi8>
    }
    %reallocated = memref.alloca() : memref<8xi8>

    %view_target = memref.view %target[%c0_v][%c8_v] : memref<8xi8> to memref<?xi8>
    %last_address = memref.get_global @last_address : memref<8xi8>
    %val_realloc = memref.load %reallocated[%c0] : memref<8xi8>
    memref.store %val_realloc, %last_address[%c0] : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      %val = memref.load %view_target[%i] : memref<?xi8>
      func.call @use(%val) : (i8) -> ()
    }

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
  %test_success = arith.constant 42 : i32
  %c0_loop = arith.constant 0 : index
  %c1_loop = arith.constant 1 : index
  %c_max_loop = arith.constant 100 : index
  %ctrue_loop = arith.constant 1 : i1
      %cfalse = arith.constant 0 : i1
  %not_matched_for = scf.for %counter = %c0_loop to %c_max_loop step %c1_loop
      iter_args(%not_matched_iter = %ctrue_loop)
      -> (i1) {
    %next_not_matched = scf.if %not_matched_iter -> (i1) {
    %ret = func.call @f() : () -> i32
      scf.yield %cfalse : i1
    } else {
      scf.yield %not_matched_iter : i1
    }
    scf.yield %next_not_matched : i1
  }
  func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }
}
