//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Memory region: stack
// Bug type: use-after-*, freed memory
// Access type: direct, write
// Variant:

module {
  // globals

  memref.global @target_address : memref<1xindex>
  memref.global @target_ptr : memref<1xmemref<8xi8>>
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> i32 {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0xFF = arith.constant 255 : i8
    %c0_i32 = arith.constant 0 : i32
    // locals

    %target = memref.alloca() : memref<8xi8>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xAA, %target[%i] : memref<8xi8>
    }

    %target_addr = memref.extract_aligned_pointer_as_index %target : memref<8xi8> -> index
    %global_addr = memref.get_global @target_address : memref<1xindex>
    memref.store %target_addr, %global_addr[%c0] : memref<1xindex>
    %global_ptr = memref.get_global @target_ptr : memref<1xmemref<8xi8>>
    memref.store %target, %global_ptr[%c0] : memref<1xmemref<8xi8>>
    %global_ptr_main = memref.get_global @target_ptr : memref<1xmemref<8xi8>>
    %saved_ptr = memref.load %global_ptr_main[%c0] : memref<1xmemref<8xi8>>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xFF, %saved_ptr[%i] : memref<8xi8>
    }
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> i32

    return %c0_i32 : i32
  }
}
