//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Variant:
//  - with repeated attempts
//  - using an array of objects

module {
  // globals

  memref.global @target_addresses : memref<16xindex>
  memref.global @target_arr : memref<1xmemref<16x8xi8>>
  func.func private @exit(%arg0: i32) -> ()
  memref.global @last_address : memref<1xindex>

  func.func @f() -> i32 {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c_arr = arith.constant 16 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
    %false = arith.constant false
    %c0xFF = arith.constant 255 : i8
    %c0_i32 = arith.constant 0 : i32
    // locals

    %reallocated = memref.alloca() : memref<8xi8>

    %target = memref.alloca() : memref<16x8xi8>
    scf.for %i = %c0 to %c_arr step %c1 {
      scf.for %j = %c0 to %c8 step %c1 {
        memref.store %c0xAA, %target[%i, %j] : memref<16x8xi8>
      }
    }
    %global_arr = memref.get_global @target_arr : memref<1xmemref<16x8xi8>>
    memref.store %target, %global_arr[%c0] : memref<1xmemref<16x8xi8>>
    %base_addr = memref.extract_aligned_pointer_as_index %target : memref<16x8xi8> -> index
    %global_addrs = memref.get_global @target_addresses : memref<16xindex>
    scf.for %i = %c0 to %c_arr step %c1 {
      %offset = arith.muli %i, %c8 : index
      %row_addr = arith.addi %base_addr, %offset : index
      memref.store %row_addr, %global_addrs[%i] : memref<16xindex>
    }
    %realloc_addr = memref.extract_aligned_pointer_as_index %reallocated : memref<8xi8> -> index
    %global_last = memref.get_global @last_address : memref<1xindex>
    %last_addr = memref.load %global_last[%c0] : memref<1xindex>
    %eq_last = arith.cmpi eq, %last_addr, %realloc_addr : index
    scf.if %eq_last {
      func.call @exit(%precond_fail) : (i32) -> ()
      scf.yield
    }
    memref.store %realloc_addr, %global_last[%c0] : memref<1xindex>
    %global_addrs_other = memref.get_global @target_addresses : memref<16xindex>
    %result:2 = scf.for %i = %c0 to %c_arr step %c1 iter_args(%found = %false, %idx = %c0) -> (i1, index) {
      %target_addr = memref.load %global_addrs_other[%i] : memref<16xindex>
      %eq = arith.cmpi eq, %realloc_addr, %target_addr : index
      %next_found = arith.ori %found, %eq : i1
      %next_idx = arith.select %eq, %i, %idx : index
      scf.yield %next_found, %next_idx : i1, index
    }
    %global_arr_access = memref.get_global @target_arr : memref<1xmemref<16x8xi8>>
    %target_loaded = memref.load %global_arr_access[%c0] : memref<1xmemref<16x8xi8>>
    scf.for %i = %c0 to %c8 step %c1 {
      memref.store %c0xFF, %target_loaded[%result#1, %i] : memref<16x8xi8>
    }

    return %c0_i32 : i32
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %c0_main = arith.constant 0 : index
    %c1_main = arith.constant 1 : index
    %cMAX_main = arith.constant 100 : index
    %test_success = arith.constant 42 : i32
    %results = scf.while (%counter = %c0_main) : (index) -> index {
      %lt = arith.cmpi slt, %counter, %cMAX_main : index
      scf.condition(%lt) %counter : index
    } do {
    ^bb0(%counter_iter : index):
    %ret = func.call @f() : () -> i32
      %next_counter = arith.addi %counter_iter, %c1_main : index
      scf.yield %next_counter : index
    }
    func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }
}
