//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Variant:
//  - with repeated attempts

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()

  func.func @f() -> memref<8xi8> {
    %c0_v = arith.constant 0 : index
    %c8_v = arith.constant 8 : index
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c_max = arith.constant 1000000000 : index
  %ctrue_loop = arith.constant 1 : i1
      %c8 = arith.constant 8 : index
      %c0xAA = arith.constant 170 : i8
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    // locals

    %target = memref.alloc() : memref<8xi8>
    %view_target = memref.view %target[%c0_v][%c8_v] : memref<8xi8> to memref<?xi8>
    memref.dealloc %target : memref<8xi8>
    %reallocated = memref.alloc() : memref<8xi8>

  %reallocated_for, %not_matched_for = scf.for %counter = %c0 to %c_max step %c1
      iter_args(%reallocated_iter = %reallocated, %not_matched_iter = %ctrue_loop)
      -> (memref<8xi8>, i1) {
    %next_reallocated, %next_not_matched = scf.if %not_matched_iter -> (memref<8xi8>, i1) {
      memref.dealloc %reallocated_iter : memref<8xi8>
      %new_reallocated = memref.alloc() : memref<8xi8>
      scf.for %i = %c0 to %c8 step %c1 {
        memref.store %c0xAA, %new_reallocated[%i] : memref<8xi8>
      }
      %target_ptr_loop = memref.extract_aligned_pointer_as_index %target : memref<8xi8> -> index
      %new_ptr_loop = memref.extract_aligned_pointer_as_index %new_reallocated : memref<8xi8> -> index
      %eq_loop = arith.cmpi eq, %target_ptr_loop, %new_ptr_loop : index
      %not_matched_next = arith.xori %eq_loop, %ctrue_loop : i1
      scf.yield %new_reallocated, %not_matched_next : memref<8xi8>, i1
    } else {
      scf.yield %reallocated_iter, %not_matched_iter : memref<8xi8>, i1
    }
    scf.yield %next_reallocated, %next_not_matched : memref<8xi8>, i1
  }
  scf.if %not_matched_for {
    func.call @exit(%precond_fail) : (i32) -> ()
  }
  scf.for %i = %c0 to %c8 step %c1 {
    %val = memref.load %view_target[%i] : memref<?xi8>
    func.call @use(%val) : (i8) -> ()
  }
  func.call @exit(%test_success) : (i32) -> ()

    

    memref.dealloc %target : memref<8xi8>
    memref.dealloc %reallocated : memref<8xi8>
    %c0_memref = memref.alloca() : memref<8xi8>
    return %c0_memref : memref<8xi8>
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> memref<8xi8>

    return %c0_i32 : i32
  }
}
