//
 // This file is distributed under the Apache License, Version 2.0; refer to
 // LICENSE for details.
 //
 // Generated by MSET-MLIR 1.0.
 ///

// Variant:
//  - using an array of objects

module {
  // globals

  func.func @use(%arg0: i8) -> () { func.return }
  func.func private @exit(%arg0: i32) -> ()
  memref.global @last_address : memref<8xi8> = dense<0>
  memref.global @target_addresses : memref<16x8xi8> = dense<0>

  func.func @other_f(%arg0:memref<8xi8>) -> i32 {
  %test_success = arith.constant 42 : i32
  %precond_fail = arith.constant 43 : i32
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c8 = arith.constant 8 : index
  %c16 = arith.constant 16 : index
  %cfalse = arith.constant 0 : i1
    %c0_i32 = arith.constant 0 : i32
    // locals
    %reallocated = memref.alloca() : memref<8xi8>
  %view_target = memref.get_global @target_addresses : memref<16x8xi8>
  %found = scf.for %counter = %c0 to %c16 step %c1 iter_args(%found_iter = %cfalse) -> (i1) {
    %realloc_ptr = memref.extract_aligned_pointer_as_index %reallocated : memref<8xi8> -> index
    %target_base = memref.extract_aligned_pointer_as_index %view_target : memref<16x8xi8> -> index
    %offset = arith.muli %counter, %c8 : index
    %target_ptr = arith.addi %target_base, %offset : index
    %eq = arith.cmpi eq, %realloc_ptr, %target_ptr : index
    %found_next = arith.ori %found_iter, %eq : i1
    scf.yield %found_next : i1
  }
  scf.if %found {
  } else {
    func.call @exit(%precond_fail) : (i32) -> ()
  }
  scf.for %i = %c0 to %c8 step %c1 {
    %val = memref.load %view_target[%c0, %i] : memref<16x8xi8>
    func.call @use(%val) : (i8) -> ()
  }
  func.call @exit(%test_success) : (i32) -> ()

    return %c0_i32 : i32
  }
  func.func @f() -> memref<8xi8> {
    %precond_fail = arith.constant 43 : i32
    %test_success = arith.constant 42 : i32
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c_arr = arith.constant 16 : index
    %c8 = arith.constant 8 : index
    %c0xAA = arith.constant 170 : i8
  %c0_v = arith.constant 0 : index
  %c8_v = arith.constant 8 : index
    // locals


    %target = memref.alloca() : memref<16x8xi8>
    scf.for %i = %c0 to %c_arr step %c1 {
      scf.for %j = %c0 to %c8 step %c1 {
        memref.store %c0xAA, %target[%i, %j] : memref<16x8xi8>
      }
    }
  %view_target = memref.subview %target[0,0][16,8][1,1] : memref<16x8xi8> to memref<16x8xi8>

    %c0_memref = memref.alloca() : memref<8xi8>
    return %c0_memref : memref<8xi8>
  }

  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %ret = func.call @f() : () -> memref<8xi8>
    %_ = func.call @other_f(%ret) : (memref<8xi8>) -> i32

    return %c0_i32 : i32
  }
}
