/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Initial author: Emanuel Vintila
 */

#include "code_canvas.h"

#include <cassert>
#include <sstream>

const std::string LICENSE =
  "//\n"
  " // This file is distributed under the Apache License, Version 2.0; refer to\n"
  " // LICENSE for details.\n"
  " //\n"
  " // Generated by MSET-MLIR 1.0.\n"
  " ///\n"
  "\n";

CodeCanvas::CodeCanvas():
  number_of_globals(0),
  number_of_locals(0)
{
  code_lines = {
    "module {",                                      // 0
    "  // globals",                                  // 1
    "",                                              // 2
    "",                                              // 3
    "  func.func @f() -> i32 {",                     // 4
    "    // locals",                                 // 5
    "",                                              // 6
    "",                                              // 7
    "",                                              // 8
    "    %c0_i32 = arith.constant 0 : i32",          // 9
    "    return %c0_i32 : i32",                      // 10
    "  }",                                           // 11
    "",                                              // 12
    "  func.func @main() -> i32 {",                  // 13
    "    %c0_i32 = arith.constant 0 : i32",          // 14
    "    %ret = func.call @f() : () -> i32",         // 15
    "",                                              // 16
    "    return %c0_i32 : i32",                      // 17
    "  }",                                           // 18
    "}"                                              // 19
  };

  global_start_pos  = 2;
  global_pos        = 3;
  locals_start_pos  = 6;
  locals_end_pos    = 7;
  start_of_f_pos    = 5;
  f_call_pos        = 15;
  current_pos_in_f  = locals_end_pos + 1;
  end_of_f_pos      = current_pos_in_f + 1;
  current_pos_in_main = f_call_pos + 1;
  current_pos_in_other_f = INVALID_CODE_POS;
  other_f_call_pos = INVALID_CODE_POS;

  // 预定义 MLIR 常量（precond_fail 必须在 Flow 返回的 precondition check 之前定义）
  add_to_f_body("%precond_fail = arith.constant 43 : i32");
  add_to_f_body("%test_success = arith.constant 42 : i32");
}

CodeCanvas::code_pos_t CodeCanvas::add_type(const std::vector<std::string> &lines)
{
  // In MLIR, types are inline with operations; add to globals area as comments or memref.global
  assert( global_pos != INVALID_CODE_POS );
  assert( global_pos < code_lines.size() );
  code_lines.insert(code_lines.begin() + global_pos, lines.begin(), lines.end());
  _update_indexes(global_pos, lines.size());
  return global_pos;
}

CodeCanvas::code_pos_t CodeCanvas::add_global(const std::string &global)
{
  assert( global_pos != INVALID_CODE_POS );
  assert( global_pos < code_lines.size() );
  code_lines.insert(code_lines.begin() + global_pos, "  " + global);
  _update_indexes(global_pos, 1);
  ++number_of_globals;
  return global_pos;
}

CodeCanvas::code_pos_t CodeCanvas::add_globals(const std::vector<std::string> &globals)
{
  code_pos_t pos = INVALID_CODE_POS;
  for ( const auto& global: globals ) pos = add_global(global);
  return pos;
}

CodeCanvas::code_pos_t CodeCanvas::add_global_first(const std::string &global)
{
  assert( global_start_pos != INVALID_CODE_POS );
  assert( global_start_pos < code_lines.size() );
  code_lines.insert(code_lines.begin() + global_start_pos, "  " + global);
  _update_indexes(global_start_pos + 1, 1);
  ++number_of_globals;
  return global_start_pos;
}

CodeCanvas::code_pos_t CodeCanvas::add_globals_first(const std::vector<std::string> &globals)
{
  code_pos_t pos = INVALID_CODE_POS;
  for ( const auto& global: globals ) pos = add_global_first(global);
  return pos;
}

CodeCanvas::code_pos_t CodeCanvas::add_local(const std::string &line)
{
  ++number_of_locals;
  return add_at(locals_end_pos, std::vector<std::string>{line}, "    ");
}

CodeCanvas::code_pos_t CodeCanvas::add_locals(const std::vector<std::string> &locals)
{
  code_pos_t pos = INVALID_CODE_POS;
  for ( const auto& local: locals ) pos = add_local(local);
  return pos;
}

CodeCanvas::code_pos_t CodeCanvas::add_local_first(const std::string &local)
{
  assert( locals_start_pos != INVALID_CODE_POS );
  assert( locals_start_pos < code_lines.size() );
  ++number_of_locals;
  code_lines.insert(code_lines.begin() + locals_start_pos, "    " + local);
  _update_indexes(locals_start_pos + 1, 1);
  return locals_start_pos + 1;
}

CodeCanvas::code_pos_t CodeCanvas::add_locals_first(const std::vector<std::string> &locals)
{
  code_pos_t pos = INVALID_CODE_POS;
  for ( const auto& local: locals ) pos = add_local_first(local);
  return pos;
}

CodeCanvas::code_pos_t CodeCanvas::add_to_custom_section(const std::vector< std::string > &vars)
{
  code_pos_t pos = INVALID_CODE_POS;
  for ( const auto& var: vars ) pos = add_global(var);
  return pos;
}

CodeCanvas::code_pos_t CodeCanvas::add_to_f_body(const std::vector<std::string> &lines)
{
  assert( current_pos_in_f != INVALID_CODE_POS );
  assert( current_pos_in_f < code_lines.size() );
  std::vector<std::string> indented_lines{lines.size()};
  for ( size_t i = 0; i < lines.size(); i++ )
  {
    indented_lines[i] = "    " + lines[i];
  }
  code_lines.insert(code_lines.begin() + current_pos_in_f, indented_lines.begin(), indented_lines.end());
  _update_indexes(current_pos_in_f, lines.size());
  return current_pos_in_f;
}

CodeCanvas::code_pos_t CodeCanvas::add_to_f_body(const std::string &line)
{
  return add_to_f_body(std::vector<std::string>{line});
}

CodeCanvas::code_pos_t CodeCanvas::add_to_f_body_end(const std::vector<std::string> &lines)
{
  assert( end_of_f_pos != INVALID_CODE_POS );
  assert( end_of_f_pos < code_lines.size() );
  std::vector<std::string> indented_lines{lines.size()};
  for ( size_t i = 0; i < lines.size(); i++ )
  {
    indented_lines[i] = "    " + lines[i];
  }
  code_lines.insert(code_lines.begin() + end_of_f_pos, indented_lines.begin(), indented_lines.end());
  _update_indexes(end_of_f_pos, lines.size());
  return end_of_f_pos;
}

CodeCanvas::code_pos_t CodeCanvas::add_to_f_body_end(const std::string &line)
{
  return add_to_f_body_end(std::vector<std::string>{line});
}

CodeCanvas::code_pos_t CodeCanvas::add_to_other_f_body(const std::vector<std::string> &lines)
{
  if ( current_pos_in_other_f == INVALID_CODE_POS )
  {
    _generate_other_f_and_call();
  }
  assert( current_pos_in_other_f < code_lines.size() );
  std::vector<std::string> indented_lines{lines.size()};
  for ( size_t i = 0; i < lines.size(); i++ )
  {
    indented_lines[i] = "    " + lines[i];
  }
  code_lines.insert(code_lines.begin() + current_pos_in_other_f, indented_lines.begin(), indented_lines.end());
  _update_indexes(current_pos_in_other_f, lines.size());
  return current_pos_in_other_f;
}

CodeCanvas::code_pos_t CodeCanvas::add_to_other_f_body(const std::string &line)
{
  return add_to_other_f_body(std::vector<std::string>{line});
}

CodeCanvas::code_pos_t CodeCanvas::add_to_main_body(const std::vector<std::string> &lines)
{
  if ( current_pos_in_main == INVALID_CODE_POS )
  {
    _generate_other_f_and_call();
  }
  assert( current_pos_in_main < code_lines.size() );
  std::vector<std::string> indented_lines{lines.size()};
  for ( size_t i = 0; i < lines.size(); i++ )
  {
    indented_lines[i] = "    " + lines[i];
  }
  code_lines.insert(code_lines.begin() + current_pos_in_main, indented_lines.begin(), indented_lines.end());
  _update_indexes(current_pos_in_main, lines.size());
  return current_pos_in_main;
}

CodeCanvas::code_pos_t CodeCanvas::add_to_main_body(const std::string &line)
{
  return add_to_main_body(std::vector<std::string>{line});
}

CodeCanvas::code_pos_t CodeCanvas::add_at(code_pos_t where, const std::vector<std::string> &lines, const std::string indent)
{
  if ( where == INVALID_CODE_POS )
  {
    std::cerr << "[FATAL] add_at called with INVALID_CODE_POS (size=" << lines.size() << ", first_line='" << (lines.empty() ? "" : lines[0]) << "')" << std::endl;
    exit(1);
  }
  assert( where < code_lines.size() );
  std::vector<std::string> indented_lines{lines.size()};
  for ( size_t i = 0; i < lines.size(); i++ )
  {
    indented_lines[i] = indent + lines[i];
  }
  code_lines.insert(code_lines.begin() + where, indented_lines.begin(), indented_lines.end());
  _update_indexes(where, lines.size());
  return where + lines.size();
}

CodeCanvas::code_pos_t CodeCanvas::add_at(code_pos_t where, const std::string &line, const std::string indent)
{
  return add_at(where, std::vector<std::string>{line}, indent);
}

CodeCanvas::code_pos_t CodeCanvas::prefix_line_with(code_pos_t where, const std::string &what)
{
  assert( where != INVALID_CODE_POS );
  assert( where < code_lines.size() );
  code_lines[where] = what + code_lines[where];
  return where;
}

std::string CodeCanvas::to_string() const
{
  std::ostringstream result;

  result << LICENSE;

  for (const auto& str : test_case_description_lines)
  {
    result << "// " << str << "\n";
  }
  result << "// Variant:\n";
  for (const auto& str : variant_description_lines)
  {
    result << "//  - " << str << "\n";
  }
  result << "\n";

  for (const auto& str : code_lines)
  {
    result << str << "\n";
  }
  return result.str();
}

void CodeCanvas::_generate_other_f_and_call()
{
  std::vector<std::string> other_f_body = {
    "  func.func @other_f() -> i32 {", // -5
    "    // locals",                     // -4
    "",                                  // -3
    "    %c0_i32 = arith.constant 0 : i32", // -2
    "    return %c0_i32 : i32",          // -1
    "  }",                               // 0
  };
  current_pos_in_other_f = add_at(global_pos + 1, other_f_body, "" ) - 4;
  other_f_call_pos = add_at(f_call_pos + 1, "%_ = func.call @other_f() : () -> i32", "    ") - 1;
}

void CodeCanvas::_update_indexes(code_pos_t from, size_t amount)
{
  auto all_positions =   {&f_call_pos, &start_of_f_pos, &end_of_f_pos, &current_pos_in_f, &global_start_pos, &global_pos,
    &current_pos_in_other_f, &current_pos_in_main, &other_f_call_pos, &locals_start_pos, &locals_end_pos};
  for (auto pos: all_positions)
  {
    if ( *pos != INVALID_CODE_POS && *pos >= from )
    {
      assert( ( *pos + amount ) < code_lines.size() );
      *pos += amount;
    }
  }
}
